/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fissmda.Employee_Subsystem;


import fissmda.DBConnection;
import fissmda.MainUI;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import static javafx.util.Duration.hours;
import javax.swing.JOptionPane;

/**
 *
 * @author Acer
 */
public class addEmployeeUI extends javax.swing.JFrame {
 Connection con = null;  
 PreparedStatement pst =null;
 ResultSet rs = null;
 
 /**
     * Creates new form addEmployeeUI
     */
    public addEmployeeUI() {
        initComponents();
        con = DBConnection.connect();
        
        
    }

    //method to check email
    
    public boolean isValidEmail(String email){
        
        int dotCount = 0;
        int atCount = 0;
        
        
        for(int i = 0;i<email.length();i++){
            if(email.charAt(i)== '@'){
                atCount++;
            }
            
            if(email.charAt(i)=='.'){
                dotCount++;
            }
        }
        
            if(dotCount>0 && atCount == 1)
            {
                return true;
            }
            else{
                return false;
            }
        }
    
   
    //method to check numeric values 
    
    public static boolean isNumeric(String str){
    
        try{
            
            double d = Double.parseDouble(str);
           
        }
        
        
        catch(NumberFormatException nfe)
        {
        return false;
        }        
        return true;
        
    }
        
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        lastname = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        fnameBox = new javax.swing.JTextField();
        nicBox = new javax.swing.JTextField();
        lnameBox = new javax.swing.JTextField();
        emailBox = new javax.swing.JTextField();
        addressBox = new javax.swing.JTextField();
        maleBut = new javax.swing.JRadioButton();
        femaleBut = new javax.swing.JRadioButton();
        rateComboBox = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        Add = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        Demo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lastname.setBackground(new java.awt.Color(51, 153, 0));
        lastname.setToolTipText("");
        lastname.setMaximumSize(new java.awt.Dimension(1276, 815));
        lastname.setMinimumSize(new java.awt.Dimension(1276, 815));
        lastname.setPreferredSize(new java.awt.Dimension(1276, 815));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("First Name");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("Last Name:");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("NIC:");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("Email :");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("Gender:");

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fissmda/ButtonImages/ADDEMP.png"))); // NOI18N
        jLabel6.setText("ADD");
        jLabel6.setMaximumSize(new java.awt.Dimension(100, 16));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setText("Address:");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel8.setText("Hourly Rate :");

        fnameBox.setBackground(new java.awt.Color(102, 204, 0));
        fnameBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fnameBoxActionPerformed(evt);
            }
        });

        nicBox.setBackground(new java.awt.Color(102, 204, 0));
        nicBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nicBoxActionPerformed(evt);
            }
        });

        lnameBox.setBackground(new java.awt.Color(102, 204, 0));

        emailBox.setBackground(new java.awt.Color(102, 204, 0));

        addressBox.setBackground(new java.awt.Color(102, 204, 0));

        maleBut.setBackground(new java.awt.Color(102, 204, 0));
        buttonGroup1.add(maleBut);
        maleBut.setText("Male");
        maleBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maleButActionPerformed(evt);
            }
        });

        femaleBut.setBackground(new java.awt.Color(102, 204, 0));
        buttonGroup1.add(femaleBut);
        femaleBut.setText("Female");
        femaleBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                femaleButActionPerformed(evt);
            }
        });

        rateComboBox.setBackground(new java.awt.Color(102, 204, 0));
        rateComboBox.setForeground(new java.awt.Color(102, 204, 0));
        rateComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Rate Rs.", "140", "160", "250", "275" }));
        rateComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rateComboBoxActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(137, 229, 45));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fissmda/ButtonImages/greenBack.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fissmda/ButtonImages/greenHome.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Add.setBackground(new java.awt.Color(0, 204, 0));
        Add.setText("ADD EMPLOYEE");
        Add.setToolTipText("");
        Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddActionPerformed(evt);
            }
        });

        Demo.setText("DEMO");
        Demo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DemoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout lastnameLayout = new javax.swing.GroupLayout(lastname);
        lastname.setLayout(lastnameLayout);
        lastnameLayout.setHorizontalGroup(
            lastnameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lastnameLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(lastnameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(lastnameLayout.createSequentialGroup()
                        .addGap(312, 312, 312)
                        .addGroup(lastnameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(lastnameLayout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fnameBox, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(lastnameLayout.createSequentialGroup()
                                .addGroup(lastnameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(lastnameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(emailBox, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nicBox, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lnameBox, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(lastnameLayout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(rateComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(lastnameLayout.createSequentialGroup()
                                .addGroup(lastnameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7))
                                .addGroup(lastnameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(lastnameLayout.createSequentialGroup()
                                        .addGap(42, 42, 42)
                                        .addComponent(maleBut)
                                        .addGap(26, 26, 26)
                                        .addComponent(femaleBut))
                                    .addGroup(lastnameLayout.createSequentialGroup()
                                        .addGap(31, 31, 31)
                                        .addComponent(addressBox, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(lastnameLayout.createSequentialGroup()
                        .addGap(184, 184, 184)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 494, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(347, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lastnameLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(lastnameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lastnameLayout.createSequentialGroup()
                        .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(168, 168, 168))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lastnameLayout.createSequentialGroup()
                        .addComponent(Demo, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(69, 69, 69)
                        .addComponent(Add, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(98, 98, 98))))
        );
        lastnameLayout.setVerticalGroup(
            lastnameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lastnameLayout.createSequentialGroup()
                .addGroup(lastnameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(lastnameLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18))
                    .addGroup(lastnameLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(156, 156, 156)
                        .addGroup(lastnameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fnameBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(37, 37, 37)
                        .addGroup(lastnameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lnameBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(lastnameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nicBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(36, 36, 36)
                        .addGroup(lastnameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(emailBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(42, 42, 42)
                        .addGroup(lastnameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(maleBut)
                            .addComponent(femaleBut))
                        .addGap(47, 47, 47)
                        .addGroup(lastnameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(addressBox, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39)
                        .addGroup(lastnameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8)
                            .addComponent(rateComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(117, 117, 117)
                        .addGroup(lastnameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(Add, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                            .addComponent(Demo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(99, 99, 99)))
                .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lastname, javax.swing.GroupLayout.PREFERRED_SIZE, 1302, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lastname, javax.swing.GroupLayout.DEFAULT_SIZE, 945, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fnameBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fnameBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fnameBoxActionPerformed

    private void nicBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nicBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nicBoxActionPerformed

    private void maleButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maleButActionPerformed

        gen = "male";

        
    }//GEN-LAST:event_maleButActionPerformed

    private void rateComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rateComboBoxActionPerformed
        
        String s = (String)rateComboBox.getSelectedItem();
       
        
        
        
    }//GEN-LAST:event_rateComboBoxActionPerformed

    private void AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddActionPerformed
        // TODO add your handling code here:
       
        
        String fName = fnameBox.getText();
        String lName = lnameBox.getText();
        String nic = nicBox.getText();
        String email = emailBox.getText();
       String addresss = addressBox.getText();
       String hRate = rateComboBox.getSelectedItem().toString(); 
//       String hrs = hoursBox.getText();
       
       
       
        int nicLength = nic.length();
       
        
        
        
       
        
        if(fName.equals("")){
        JOptionPane.showMessageDialog(null,"First Name is Mandatory");
            
        }
        
        else if(lName.equals("")){
        JOptionPane.showMessageDialog(null,"Last Name is Mandatory");
            
        }
        
        else if(nic.equals("")){
        JOptionPane.showMessageDialog(null,"NIC is Mandatory");
            
        }
        
        else if(!(nicLength == 10 && (nic.charAt(nicLength - 1)== 'v' ||nic.charAt(nicLength - 1)== 'V' ))){
        JOptionPane.showMessageDialog(null,"Please enter a valid NIC number");
            
        }
        
        
        
        else if(email.equals("")){
        JOptionPane.showMessageDialog(null,"Email is Mandatory");
            
        }        
                
          else if(! isValidEmail(email)){
            JOptionPane.showMessageDialog(null,"Please Enter a valid Email");
        }         
                
        
                
             
        
        else if(addresss.equals("")){
        JOptionPane.showMessageDialog(null,"Address is Mandatory");
            
        }
        
        else if(hRate.equals("Rate Rs.")){
        JOptionPane.showMessageDialog(null,"Please select a valid Hourly Rate");
            
        }
        
        else if(! isNumeric(hRate)){
        JOptionPane.showMessageDialog(null,"Please select a valid Hourly Rate");
        }
        
        
        
//        else if(hrs.equals("")){
//        JOptionPane.showMessageDialog(null,"Hours is Mandatory");
           
//       }
        
//          else if(! isNumeric(hrs)){
//        JOptionPane.showMessageDialog(null,"Please select a valid numer for Hours");
//          }
//        
//       
        
       
        
        
                
        else{
        
        try{
            
          float hhRate = Float.parseFloat(hRate); 
//          float hhrs = Float.parseFloat(hrs);
//          float sal = hhrs * hhRate ;
            
        String q ="INSERT INTO employee(firstName,lastName,nic,email,gender,address,hourly_rate) values('"+fName+"','"+lName+"','"+nic +"', '" +email+"','"+gen+"','"+addresss+"','"+hhRate+"')";
        pst = con.prepareStatement(q);
        pst.execute();
       
        JOptionPane.showMessageDialog(null,"Added");
       
        }
        catch(Exception e){
    }//GEN-LAST:event_AddActionPerformed
    }}
    private void femaleButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_femaleButActionPerformed
        // TODO add your handling code here:
        gen = "female";
        
        
    }//GEN-LAST:event_femaleButActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
            EmployeeUI e1 = new EmployeeUI();
        e1.setVisible(true);
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        e1.setLocation(dim.width/2-this.getSize().width/2,dim.height/2-this.getSize().height/2);
        this.dispose();
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
               MainUI e1 = new MainUI();
        e1.setVisible(true);
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        e1.setLocation(dim.width/2-this.getSize().width/2,dim.height/2-this.getSize().height/2);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void DemoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DemoActionPerformed
        // TODO add your handling code here:
        fnameBox.setText("vishaka");
        lnameBox.setText("liyanage");
        nicBox.setText("456788444V");
        emailBox.setText("sunil@gmail.com");
        addressBox.setText("kurunagala");
        
    }//GEN-LAST:event_DemoActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addEmployeeUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addEmployeeUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addEmployeeUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addEmployeeUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addEmployeeUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add;
    private javax.swing.JButton Demo;
    private javax.swing.JTextField addressBox;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField emailBox;
    private javax.swing.JRadioButton femaleBut;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JTextField fnameBox;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel lastname;
    private javax.swing.JTextField lnameBox;
    private javax.swing.JRadioButton maleBut;
    private javax.swing.JTextField nicBox;
    private javax.swing.JComboBox<String> rateComboBox;
    // End of variables declaration//GEN-END:variables

private String gen;

}
