/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fissmda.Manager_Subsystem;

import fissmda.DBConnection;
import fissmda.MainUI;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Romesh
 */
public class AddManagerUI extends javax.swing.JFrame {

    
    Connection con = null;
    PreparedStatement pst = null; 
    ResultSet rs = null;
    
    
    
    
    /**
     * Creates new form AddManagerUI
     */
    public AddManagerUI() {
        initComponents();
        
        con = DBConnection.connect();
        
    }
    
    
    //method to check whether username is taken
    public boolean isUsernameUsed(String username){
        
        try {
            String query = "SELECT * FROM manager WHERE username = ?";
            PreparedStatement pst = con.prepareStatement(query);
            
            pst.setString(1, username);
            rs = pst.executeQuery();
            
            if(rs.next()){
                return true;
            }
            else{
                return false;
            }
        } catch (SQLException ex) {
            Logger.getLogger(AddManagerUI.class.getName()).log(Level.SEVERE, null, ex);
            return false;
        }
    }
    
       //method to check whether NIC is taken
    public boolean isNICUsed(String nic){
        
        try {
            String query = "SELECT * FROM manager WHERE nic = ?";
            PreparedStatement pst = con.prepareStatement(query);
            
            pst.setString(1, nic);
            rs = pst.executeQuery();
            
            if(rs.next()){
                return true;
            }
            else{
                return false;
            }
        } catch (SQLException ex) {
            Logger.getLogger(AddManagerUI.class.getName()).log(Level.SEVERE, null, ex);
            return false;
        }
    }
    
    //method to v
    public int vgana(String nic){
        int count = 0;
    for(int i = 0 ; i< nic.length(); i++ ){
    
        if(nic.charAt(i) == 'V' || nic.charAt(i) == 'v'){
            count++;
        }
    }
    
    return count;
    }
    
    
   //method to check email
    public boolean isValidEmail(String email){
    
        int dotCount = 0;
        int atCount = 0;
        
        for(int i =0 ; i < email.length() ; i++ ){
            
            if(email.charAt(i) == '@'){
            
                atCount++;
            }
            
            if(email.charAt(i) == '.'){
            
                dotCount++;
            }
        }
        
        if(dotCount > 0 && atCount == 1){
            return true;
        }
        else{
        
            return false;
        }
    }
    
    
    //is Numeric method
    
    public static boolean isNumeric(String str)  
{  
  try  
  {  
    double d = Double.parseDouble(str);  
  }  
  catch(NumberFormatException nfe)  
  {  
    return false;  
  }  
  return true;  
}
    
    //is Symbol method
    public static boolean isSymbol(String s)
    {
    
        Pattern pattern = Pattern.compile("[a-zA-Z]*");
        Matcher matcher = pattern.matcher(s);
        
        if(!matcher.matches()){
           return true;     
        }
        else{
        
            return false;
        }
    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        mFName = new javax.swing.JTextField();
        mLName = new javax.swing.JTextField();
        mNic = new javax.swing.JTextField();
        mEmail = new javax.swing.JTextField();
        maleButton = new javax.swing.JRadioButton();
        femaleButton = new javax.swing.JRadioButton();
        combo1 = new javax.swing.JComboBox<>();
        unameBox = new javax.swing.JTextField();
        passwordBox = new javax.swing.JPasswordField();
        confirmpasswordBox = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        addresstext = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        pn1 = new javax.swing.JTextField();
        pn2 = new javax.swing.JTextField();
        pn3 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        endDateC = new com.toedter.calendar.JDateChooser();
        jLabel11 = new javax.swing.JLabel();
        demoBut = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(153, 153, 91));
        jPanel1.setMaximumSize(new java.awt.Dimension(1276, 815));
        jPanel1.setMinimumSize(new java.awt.Dimension(1276, 815));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("First name");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Last Name");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("National Identity Card No");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("e-mail");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Gender");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Address");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Hourly Rate");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setText("User Name");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setText("Password");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel14.setText("Confirm Password");

        mFName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mFNameActionPerformed(evt);
            }
        });

        mNic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mNicActionPerformed(evt);
            }
        });

        buttonGroup1.add(maleButton);
        maleButton.setText("Male");
        maleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maleButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(femaleButton);
        femaleButton.setText("Female");
        femaleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                femaleButtonActionPerformed(evt);
            }
        });

        combo1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Hourly Rate Rs.", "140", "160", "250", "275" }));
        combo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo1ActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(255, 102, 102));
        jButton1.setText("Cancel");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(102, 204, 0));
        jButton2.setText("OK");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(137, 229, 45));
        jPanel2.setPreferredSize(new java.awt.Dimension(350, 58));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fissmda/ButtonImages/greenHome.png"))); // NOI18N
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fissmda/ButtonImages/greenBack.png"))); // NOI18N
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(709, Short.MAX_VALUE))
        );

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fissmda/ButtonImages/ADDmANAGERBanner.png"))); // NOI18N

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("Phone No");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("End Date");

        jLabel11.setText("( End Date is not Mandatory)");

        demoBut.setText("Demo");
        demoBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                demoButActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel10)
                            .addComponent(jLabel8)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(192, 192, 192)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(maleButton)
                                    .addGap(27, 27, 27)
                                    .addComponent(femaleButton)
                                    .addGap(381, 381, 381))
                                .addComponent(mEmail, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(mFName)
                                    .addComponent(mLName)
                                    .addComponent(mNic, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(168, 168, 168)
                                .addComponent(jButton1)
                                .addGap(18, 18, 18)
                                .addComponent(jButton2)
                                .addGap(39, 39, 39)
                                .addComponent(demoBut))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(unameBox, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(addresstext, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(confirmpasswordBox, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(passwordBox, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(endDateC, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(combo1, javax.swing.GroupLayout.Alignment.LEADING, 0, 224, Short.MAX_VALUE)
                                .addComponent(pn3, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(pn2, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(pn1, javax.swing.GroupLayout.Alignment.LEADING))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(215, 215, 215)
                        .addComponent(jLabel9)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(mFName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(mLName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(mNic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(mEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(maleButton)
                            .addComponent(femaleButton)
                            .addComponent(jLabel5))
                        .addGap(36, 36, 36)
                        .addComponent(addresstext, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pn1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pn2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pn3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(combo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8)
                    .addComponent(endDateC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel13)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel14))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(unameBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(passwordBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(confirmpasswordBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(demoBut))
                .addGap(24, 24, 24))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 841, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mFNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mFNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mFNameActionPerformed

    private void maleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maleButtonActionPerformed
        
        //male button
        gender = "Male";
        
        
        
    }//GEN-LAST:event_maleButtonActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        String fname = mFName.getText();
        String lname = mLName.getText();
        String nic = mNic.getText();
        String email = mEmail.getText();
        String addres = addresstext.getText();
        
        String phn1 = pn1.getText();
        String phn2 = pn2.getText();
        String phn3 = pn3.getText();
        
        
        String hRate = combo1.getSelectedItem().toString();
      //  String hourss = hourBox.getText(); 
       
        String uname = unameBox.getText();
        String pass = passwordBox.getText();
        String cpass = confirmpasswordBox.getText();
        
        
        
        
        
        
        
        int nicLength = nic.length();
        int phn1Length = phn1.length();
        int phn2Length = phn2.length();
        int phn3Length = phn3.length();
        
        
        if(fname.equals("")){
            JOptionPane.showMessageDialog(null,"First Name is Mandotory");
        }
        
       
        else if (isSymbol(fname)){
        
            JOptionPane.showMessageDialog(null,"Enter a valid First Name without Symbols or Numbers");
        }
        
        else if(lname.equals("")){
            JOptionPane.showMessageDialog(null,"Last Name is Mandotory");
        }
        
        else if (isSymbol(lname)){
        
            JOptionPane.showMessageDialog(null,"Enter a valid Last Name without Symbols or Numbers");
        }
        
      
        
        else if(nic.equals("")){
            JOptionPane.showMessageDialog(null,"National Identity Card Number is Mandotory");
        }
        
        
        
        else if(!(nicLength == 10 && (nic.charAt(nicLength-1) == 'V' || nic.charAt(nicLength-1) == 'v')) || !(vgana(nic) == 1 )){
            JOptionPane.showMessageDialog(null,"Invalid National Identity Card Number");
            
        }
        
        
        
        else if(isNICUsed(nic)){
            JOptionPane.showMessageDialog(null, "NIC is already taken");
        }
        
        
        else if(email.equals("")){
            JOptionPane.showMessageDialog(null,"e-mail is Mandotory");
        }
        
        
        else if(! isValidEmail(email)){
        
            JOptionPane.showMessageDialog(null, "Please input a valid e-mail");
        }
        
        else if(!(maleButton.isSelected() || femaleButton.isSelected()) ){
            JOptionPane.showMessageDialog(null,"Please select the Gender");
        }
        
        else if(addres.equals("")){
            JOptionPane.showMessageDialog(null,"Address is Mandotory");
        }
        
        
        else if(phn1.equals("")){
            JOptionPane.showMessageDialog(null,"One Phone Number of a Manager is Mandotory");
        }
        
        else if(! ((isNumeric(phn1)) && ( phn1Length == 10))){
 
            JOptionPane.showMessageDialog(null,"Invalid First Phone Number. Insert a Valid phone Number with No symbols or Characters.");
            
        }
        
        
        
         else if (! phn2.equals("") && (! ((isNumeric(phn2)) && ( phn2Length == 10)) )){
        
            
 
            JOptionPane.showMessageDialog(null,"Invalid Second Phone Number. Insert a Valid phone Number with No Symbols or Characters.");
            
        }
     
        
        
         else if (! phn3.equals("") && (! ((isNumeric(phn3)) && ( phn3Length == 10)) )){
            
 
            JOptionPane.showMessageDialog(null,"Invalid Theird Phone Number. Insert a Valid phone Number with No Symbols or Characters.");
            
        }
         
         

        else if(endDateC.getDate()== null){
        
             JOptionPane.showMessageDialog(null,"end date is mandotary");
             
         }
        
        
        
       
            
        
        
        else if(hRate.equals("")){
            JOptionPane.showMessageDialog(null,"Hourly Rate is Mandotory");
        }
        
        else if(hRate.equals("Select Hourly Rate Rs.")){
            JOptionPane.showMessageDialog(null,"Select a valid Hourly Rate");
        }
        
//        else if (! isNumeric(hourss)){
//        
//            JOptionPane.showMessageDialog(null,"Please insert a Valid number to Hours");
//            
//        }
        
        
//        else if(endDateC.getDate() == null){
//        
//            JOptionPane.showMessageDialog(null,"");
//        }
         
        else if(uname.equals("")){
            JOptionPane.showMessageDialog(null,"User name is Mandotory");
        }
        else if(isUsernameUsed(uname)){
            JOptionPane.showMessageDialog(null, "Username is already taken Please change the Username");
        }
        
          else if(pass.equals("")){
            JOptionPane.showMessageDialog(null,"Password is Mandotory");
        }
        
        else if(!pass.equals(cpass)){
            JOptionPane.showMessageDialog(null, "Password does not match. Re-enter");
            confirmpasswordBox.setText(null);
        }
       
        

        
        else{
        try {
            
         float hrate = Float.parseFloat(hRate);
         float hoursee = 100;
         
         sal = hrate * hoursee;
         
         
         
         
      
        
         
        Date edate = new Date(endDateC.getDate().getTime());
        
            
        String q = "INSERT INTO manager(firstName,lastName,nic,email,gender,address,hourly_rate,hours,endDate, salary, username,password) values('"+fname +"','"+lname +"','"+nic +"','"+email +"' ,'"+gender +"', '"+addres +"' , '"+hrate +"','"+hoursee+"','"+edate +"','"+sal +"' ,'"+uname +"','"+cpass +"')";
        pst= con.prepareStatement(q);
        pst.execute();
        
     
        
       String q2 = "SELECT eid from manager where nic = '"+nic +"' ";
       PreparedStatement pst1 = con.prepareStatement(q2);
       ResultSet rs1 = pst1.executeQuery(q2);
       
       int eeiid = 0;
       while(rs1.next()){
           eeiid = rs1.getInt("eid");
       }
       
       System.out.println(eeiid);
       System.out.println(phn1);
       
       String insertPhone = "INSERT INTO manager_phone(eid, phone) VALUES('"+eeiid+"', '"+phn1+"')";
       PreparedStatement ps4 = con.prepareStatement(insertPhone);
       ps4.executeUpdate();
       
       if(!phn2.equals("")){
           String insertPhone2 = "INSERT INTO manager_phone(eid, phone) VALUES('"+eeiid+"', '"+phn2+"')";
           PreparedStatement ps5 = con.prepareStatement(insertPhone2);
           ps5.executeUpdate();
       }
       
       if(!phn3.equals("")){
           String insertPhone3 = "INSERT INTO manager_phone(eid, phone) VALUES('"+eeiid+"', '"+phn3+"')";
           PreparedStatement ps6 = con.prepareStatement(insertPhone3);
           ps6.executeUpdate();
       }
     
       
        JOptionPane.showMessageDialog(null,"Manager Successfully Added");
            
        }catch (SQLException e){
        }
        
        }
        
        
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void mNicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mNicActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mNicActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       
        //navigate to main UI
        
        MainUI m1 = new MainUI();
        m1.setVisible(true);
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        m1.setLocation(dim.width/2-this.getSize().width/2,dim.height/2-this.getSize().height/2);
        this.dispose();
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        
        //navigate to managerUI
        SelectAddManager m3 = new SelectAddManager();
        m3.setVisible(true);
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        m3.setLocation(dim.width/2-this.getSize().width/2,dim.height/2-this.getSize().height/2);
        this.dispose();
        
        
        
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void femaleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_femaleButtonActionPerformed
        
        //female button
        
        gender = "Female";
    }//GEN-LAST:event_femaleButtonActionPerformed

    private void combo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo1ActionPerformed
        
        String s = (String) combo1.getSelectedItem();
        JOptionPane.showMessageDialog(this," You have Selected " + s);
        
        
    }//GEN-LAST:event_combo1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        //clear by renavigating
        AddManagerUI m9 = new AddManagerUI();
        m9.setVisible(true);
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        m9.setLocation(dim.width/2-this.getSize().width/2,dim.height/2-this.getSize().height/2);
        this.dispose();
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void demoButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_demoButActionPerformed
        // demo but
        
        String fnamex = "Roy";
        String lnamex = "Perera";
        String nicx = "947452368V";
        String emailx = "roy@gmail.com";
        String addresx = "no 135 Kandy";
       
    
        
        String phn1x = "0116547895";
        String phn2x = "0771458962";
        String phn3x = "0716548965";
        
       // String hRatex = combo1.getSelectedItem().toString();
      //  String hourss = hourBox.getText(); 
       
        String unamex = "roy123";
        String passx = "abc";
        String cpassx = "abc";
        
        mFName.setText(fnamex);
        mLName.setText(lnamex);
        mNic.setText(nicx);
        mEmail.setText(emailx);
        addresstext.setText(addresx);
        combo1.setSelectedItem("275");
        
        maleButton.setSelected(true);
        gender = "Male";
      
        
        pn1.setText(phn1x);
        pn2.setText(phn2x);
        pn3.setText(phn3x);
        
        unameBox.setText(unamex);
        passwordBox.setText(passx);
        confirmpasswordBox.setText(cpassx);
        
        
        
        
    }//GEN-LAST:event_demoButActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddManagerUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddManagerUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddManagerUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddManagerUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddManagerUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addresstext;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> combo1;
    private javax.swing.JPasswordField confirmpasswordBox;
    private javax.swing.JButton demoBut;
    private com.toedter.calendar.JDateChooser endDateC;
    private javax.swing.JRadioButton femaleButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField mEmail;
    private javax.swing.JTextField mFName;
    private javax.swing.JTextField mLName;
    private javax.swing.JTextField mNic;
    private javax.swing.JRadioButton maleButton;
    private javax.swing.JPasswordField passwordBox;
    private javax.swing.JTextField pn1;
    private javax.swing.JTextField pn2;
    private javax.swing.JTextField pn3;
    private javax.swing.JTextField unameBox;
    // End of variables declaration//GEN-END:variables

    private String gender;
    private float sal;
}
