/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fissmda;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author Romesh
 */
public class MonthlySummaryIncome extends javax.swing.JFrame {

    Connection con = null;
    PreparedStatement pst55 = null; 
    ResultSet rs66 = null;
    
    
    PreparedStatement pstm1 = null; 
    ResultSet rsm1 = null;
    
    PreparedStatement pstm2 = null; 
    ResultSet rsm2 = null;
    
    PreparedStatement pstm3 = null; 
    ResultSet rsm3 = null;
    
    PreparedStatement pstm4 = null; 
    ResultSet rsm4 = null;
    
    PreparedStatement pstm5 = null; 
    ResultSet rsm5 = null;
    
    PreparedStatement pstm6 = null; 
    ResultSet rsm6 = null;
    
    PreparedStatement pstm7 = null; 
    ResultSet rsm7 = null;
    
    PreparedStatement pstm8 = null; 
    ResultSet rsm8 = null;
    
    PreparedStatement pstm9 = null; 
    ResultSet rsm9 = null;
    
    PreparedStatement pstm10 = null; 
    ResultSet rsm10 = null;
    
    PreparedStatement pstm11 = null; 
    ResultSet rsm11 = null;
    
    PreparedStatement pstm12 = null; 
    ResultSet rsm12 = null;
    
    
    
    
    /**
     * Creates new form MonthlySummaryIncome
     */
    public MonthlySummaryIncome() {
        initComponents();
        
        con = DBConnection.connect();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        pnlReport2 = new javax.swing.JPanel();
        combo4 = new javax.swing.JComboBox<>();
        showBut = new javax.swing.JButton();
        comBut = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 91));
        jPanel1.setMaximumSize(new java.awt.Dimension(1276, 815));
        jPanel1.setMinimumSize(new java.awt.Dimension(1276, 815));
        jPanel1.setPreferredSize(new java.awt.Dimension(1276, 815));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fissmda/ButtonImages/monthlysumbanner.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("MONTHLY  INCOME");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fissmda/ButtonImages/backB.png"))); // NOI18N
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fissmda/ButtonImages/homeB.png"))); // NOI18N
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        pnlReport2.setBackground(new java.awt.Color(187, 224, 103));
        pnlReport2.setLayout(new javax.swing.BoxLayout(pnlReport2, javax.swing.BoxLayout.LINE_AXIS));

        combo4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Year", "2017", "2018" }));
        combo4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo4ActionPerformed(evt);
            }
        });

        showBut.setBackground(new java.awt.Color(204, 245, 75));
        showBut.setText("Show");
        showBut.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        showBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showButActionPerformed(evt);
            }
        });

        comBut.setBackground(new java.awt.Color(240, 242, 114));
        comBut.setText("Compare");
        comBut.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        comBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comButActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel3.setText("Compare Monthly Income of the Agency by Year ");

        jLabel10.setText("( Right click on the bar chart to see properties [ zoom in | zoom out | print | save as photo ] )");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(combo4, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(showBut, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(158, 158, 158)
                        .addComponent(jLabel1)))
                .addContainerGap(383, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(167, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(509, 509, 509))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comBut, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(87, 87, 87))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(pnlReport2, javax.swing.GroupLayout.PREFERRED_SIZE, 955, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(154, 154, 154))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addGap(28, 28, 28))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(comBut, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(showBut, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(combo4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(pnlReport2, javax.swing.GroupLayout.PREFERRED_SIZE, 471, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        //navigate to back
        MonthlySummaryType g1 = new MonthlySummaryType();
        g1.setVisible(true);
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        g1.setLocation(dim.width/2-this.getSize().width/2,dim.height/2-this.getSize().height/2);
        this.dispose();
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void showButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showButActionPerformed
        
       
        String year = combo4.getSelectedItem().toString();
        
        
        if(year == "Select Year"){
        
            JOptionPane.showMessageDialog(null,"Please select Year");    
            
        }
       
        
        else if(year == "2017"){
        
             try{
                String sqln1 = "SELECT SUM(totalAmount) As jan FROM shop_income WHERE iDate >= '2017/01/01' and iDate <= '2017/01/31' ";
                 pstm1 = con.prepareStatement(sqln1);
                 rsm1 = pstm1.executeQuery(); 
               
        
                 if(rsm1.next()){
        
                         String total = rsm1.getString("jan");
                         System.out.println(total);
            
                         if(total == null){
            
                             jantot = 0;
                         }
                          else if(total != null){
                             Double tot = Double.parseDouble(total);
            
                             jantot = tot;
                         }
                     }
            
              }catch(SQLException e){}
             
             
             try{
                String sqln2 = "SELECT SUM(totalAmount) As feb FROM shop_income WHERE iDate >= '2017/02/01' and iDate <= '2017/02/31' ";
                 pstm2 = con.prepareStatement(sqln2);
                 rsm2 = pstm2.executeQuery(); 
              
        
                 if(rsm2.next()){
        
                         String total = rsm2.getString("feb");
                         System.out.println(total);
            
                         if(total == null){
            
                             febtot = 0;
                         }
                          else if(total != null){
                             Double tot = Double.parseDouble(total);
            
                             febtot = tot;
                         }
                     }
            
              }catch(SQLException e){}
             
             try{
                String sqln3 = "SELECT SUM(totalAmount) As mar FROM shop_income WHERE iDate >= '2017/03/01' and iDate <= '2017/03/31' ";
                 pstm3 = con.prepareStatement(sqln3);
                 rsm3 = pstm3.executeQuery(); 
               
        
                 if(rsm3.next()){
        
                         String total = rsm3.getString("mar");
                         System.out.println(total);
            
                         if(total == null){
            
                             martot = 0;
                         }
                          else if(total != null){
                             Double tot = Double.parseDouble(total);
            
                             martot = tot;
                         }
                     }
            
              }catch(SQLException e){}
             
             
             try{
                String sqln4 = "SELECT SUM(totalAmount) As apr FROM shop_income WHERE iDate >= '2017/04/01' and iDate <= '2017/04/31' ";
                 pstm4 = con.prepareStatement(sqln4);
                 rsm4 = pstm4.executeQuery(); 
               
        
                 if(rsm4.next()){
        
                         String total = rsm4.getString("apr");
                         System.out.println(total);
            
                         if(total == null){
            
                             aprtot = 0;
                         }
                          else if(total != null){
                             Double tot = Double.parseDouble(total);
            
                             aprtot = tot;
                         }
                     }
            
              }catch(SQLException e){}
             
             try{
                String sqln5 = "SELECT SUM(totalAmount) As may FROM shop_income WHERE iDate >= '2017/05/01' and iDate <= '2017/05/31' ";
                 pstm5 = con.prepareStatement(sqln5);
                 rsm5 = pstm5.executeQuery(); 
              
        
                 if(rsm5.next()){
        
                         String total = rsm5.getString("may");
                         System.out.println(total);
            
                         if(total == null){
            
                             maytot = 0;
                         }
                          else if(total != null){
                             Double tot = Double.parseDouble(total);
            
                             maytot = tot;
                         }
                     }
            
              }catch(SQLException e){}
             
             
             try{
                String sqln6 = "SELECT SUM(totalAmount) As jun FROM shop_income WHERE iDate >= '2017/06/01' and iDate <= '2017/06/31' ";
                 pstm6 = con.prepareStatement(sqln6);
                 rsm6 = pstm6.executeQuery(); 
             
        
                 if(rsm6.next()){
        
                         String total = rsm6.getString("jun");
                         System.out.println(total);
            
                         if(total == null){
            
                             juntot = 0;
                         }
                          else if(total != null){
                             Double tot = Double.parseDouble(total);
            
                             juntot = tot;
                         }
                     }
            
              }catch(SQLException e){}
             
             
             try{
                String sqln7 = "SELECT SUM(totalAmount) As jul FROM shop_income WHERE iDate >= '2017/07/01' and iDate <= '2017/07/31' ";
                 pstm7 = con.prepareStatement(sqln7);
                 rsm7 = pstm7.executeQuery(); 
              
        
                 if(rsm7.next()){
        
                         String total = rsm7.getString("jul");
                         System.out.println(total);
            
                         if(total == null){
            
                             juntot = 0;
                         }
                          else if(total != null){
                             Double tot = Double.parseDouble(total);
            
                             juntot = tot;
                         }
                     }
            
              }catch(SQLException e){}
             
             
             try{
                String sqln8 = "SELECT SUM(totalAmount) As aug FROM shop_income WHERE iDate >= '2017/08/01' and iDate <= '2017/08/31' ";
                 pstm8 = con.prepareStatement(sqln8);
                 rsm8 = pstm8.executeQuery(); 
             
        
                 if(rsm8.next()){
        
                         String total = rsm8.getString("aug");
                         System.out.println(total);
            
                         if(total == null){
            
                             augtot = 0;
                         }
                          else if(total != null){
                             Double tot = Double.parseDouble(total);
            
                             augtot = tot;
                         }
                     }
            
              }catch(SQLException e){}
             
             
             try{
                String sqln9 = "SELECT SUM(totalAmount) As sep FROM shop_income WHERE iDate >= '2017/09/01' and iDate <= '2017/09/31' ";
                 pstm9 = con.prepareStatement(sqln9);
                 rsm9 = pstm9.executeQuery(); 
              
        
                 if(rsm9.next()){
        
                         String total = rsm9.getString("sep");
                         System.out.println(total);
            
                         if(total == null){
            
                             septot = 0;
                         }
                          else if(total != null){
                             Double tot = Double.parseDouble(total);
            
                             septot = tot;
                         }
                     }
            
              }catch(SQLException e){}
             
             
             try{
                String sqln10 = "SELECT SUM(totalAmount) As oct FROM shop_income WHERE iDate >= '2017/10/01' and iDate <= '2017/10/31' ";
                 pstm10 = con.prepareStatement(sqln10);
                 rsm10 = pstm10.executeQuery(); 
            
        
                 if(rsm10.next()){
        
                         String total = rsm10.getString("oct");
                         System.out.println(total);
            
                         if(total == null){
            
                             octtot = 0;
                         }
                          else if(total != null){
                             Double tot = Double.parseDouble(total);
            
                             octtot = tot;
                         }
                     }
            
              }catch(SQLException e){}
             
             
             try{
                String sqln11 = "SELECT SUM(totalAmount) As nov FROM shop_income WHERE iDate >= '2017/11/01' and iDate <= '2017/11/31' ";
                 pstm11 = con.prepareStatement(sqln11);
                 rsm11 = pstm11.executeQuery(); 
              
        
                 if(rsm11.next()){
        
                         String total = rsm11.getString("nov");
                         System.out.println(total);
            
                         if(total == null){
            
                             novtot = 0;
                         }
                          else if(total != null){
                             Double tot = Double.parseDouble(total);
            
                             novtot = tot;
                         }
                     }
            
              }catch(SQLException e){}
             
             
             try{
                String sqln12 = "SELECT SUM(totalAmount) As dec FROM shop_income WHERE iDate >= '2017/12/01' and iDate <= '2017/12/31' ";
                 pstm12 = con.prepareStatement(sqln12);
                 rsm12 = pstm12.executeQuery(); 
              
        
                 if(rsm12.next()){
        
                         String total = rsm12.getString("dec");
                         System.out.println(total);
            
                         if(total == null){
            
                             dectot = 0;
                         }
                          else if(total != null){
                             Double tot = Double.parseDouble(total);
            
                             dectot = tot;
                         }
                     }
            
              }catch(SQLException e){}
             
             
        }
             
            //******************************2018********************************************
            
            else if(year == "2018"){
                    
                 
                try{
                String sqln1 = "SELECT SUM(totalAmount) As jan FROM shop_income WHERE iDate >= '2018/01/01' and iDate <= '2018/01/31' ";
                 pstm1 = con.prepareStatement(sqln1);
                 rsm1 = pstm1.executeQuery(); 
               
        
                 if(rsm1.next()){
        
                         String total = rsm1.getString("jan");
                         System.out.println(total);
            
                         if(total == null){
            
                             jantot = 0;
                         }
                          else if(total != null){
                             Double tot = Double.parseDouble(total);
            
                             jantot = tot;
                         }
                     }
            
              }catch(SQLException e){}
             
             
             try{
                String sqln2 = "SELECT SUM(totalAmount) As feb FROM shop_income WHERE iDate >= '2018/02/01' and iDate <= '2018/02/31' ";
                 pstm2 = con.prepareStatement(sqln2);
                 rsm2 = pstm2.executeQuery(); 
              
        
                 if(rsm2.next()){
        
                         String total = rsm2.getString("feb");
                         System.out.println(total);
            
                         if(total == null){
            
                             febtot = 0;
                         }
                          else if(total != null){
                             Double tot = Double.parseDouble(total);
            
                             febtot = tot;
                         }
                     }
            
              }catch(SQLException e){}
             
             try{
                String sqln3 = "SELECT SUM(totalAmount) As mar FROM shop_income WHERE iDate >= '2018/03/01' and iDate <= '2018/03/31' ";
                 pstm3 = con.prepareStatement(sqln3);
                 rsm3 = pstm3.executeQuery(); 
               
        
                 if(rsm3.next()){
        
                         String total = rsm3.getString("mar");
                         System.out.println(total);
            
                         if(total == null){
            
                             martot = 0;
                         }
                          else if(total != null){
                             Double tot = Double.parseDouble(total);
            
                             martot = tot;
                         }
                     }
            
              }catch(SQLException e){}
             
             
             try{
                String sqln4 = "SELECT SUM(totalAmount) As apr FROM shop_income WHERE iDate >= '2018/04/01' and iDate <= '2018/04/31' ";
                 pstm4 = con.prepareStatement(sqln4);
                 rsm4 = pstm4.executeQuery(); 
              
        
                 if(rsm4.next()){
        
                         String total = rsm4.getString("apr");
                         System.out.println(total);
            
                         if(total == null){
            
                             aprtot = 0;
                         }
                          else if(total != null){
                             Double tot = Double.parseDouble(total);
            
                             aprtot = tot;
                         }
                     }
            
              }catch(SQLException e){}
             
             try{
                String sqln5 = "SELECT SUM(totalAmount) As may FROM shop_income WHERE iDate >= '2018/05/01' and iDate <= '2018/05/31' ";
                 pstm5 = con.prepareStatement(sqln5);
                 rsm5 = pstm5.executeQuery(); 
             
        
                 if(rsm5.next()){
        
                         String total = rsm5.getString("may");
                         System.out.println(total);
            
                         if(total == null){
            
                             maytot = 0;
                         }
                          else if(total != null){
                             Double tot = Double.parseDouble(total);
            
                             maytot = tot;
                         }
                     }
            
              }catch(SQLException e){}
             
             
             try{
                String sqln6 = "SELECT SUM(totalAmount) As jun FROM shop_income WHERE iDate >= '2018/06/01' and iDate <= '2018/06/31' ";
                 pstm6 = con.prepareStatement(sqln6);
                 rsm6 = pstm6.executeQuery(); 
             
        
                 if(rsm6.next()){
        
                         String total = rsm6.getString("jun");
                         System.out.println(total);
            
                         if(total == null){
            
                             juntot = 0;
                         }
                          else if(total != null){
                             Double tot = Double.parseDouble(total);
            
                             juntot = tot;
                         }
                     }
            
              }catch(SQLException e){}
             
             
             try{
                String sqln7 = "SELECT SUM(totalAmount) As jul FROM shop_income WHERE iDate >= '2018/07/01' and iDate <= '2018/07/31' ";
                 pstm7 = con.prepareStatement(sqln7);
                 rsm7 = pstm7.executeQuery(); 
            
        
                 if(rsm7.next()){
        
                         String total = rsm7.getString("jul");
                         System.out.println(total);
            
                         if(total == null){
            
                             juntot = 0;
                         }
                          else if(total != null){
                             Double tot = Double.parseDouble(total);
            
                             juntot = tot;
                         }
                     }
            
              }catch(SQLException e){}
             
             
             try{
                String sqln8 = "SELECT SUM(totalAmount) As aug FROM shop_income WHERE iDate >= '2018/08/01' and iDate <= '2018/08/31' ";
                 pstm8 = con.prepareStatement(sqln8);
                 rsm8 = pstm8.executeQuery(); 
              
        
                 if(rsm8.next()){
        
                         String total = rsm8.getString("aug");
                         System.out.println(total);
            
                         if(total == null){
            
                             augtot = 0;
                         }
                          else if(total != null){
                             Double tot = Double.parseDouble(total);
            
                             augtot = tot;
                         }
                     }
            
              }catch(SQLException e){}
             
             
             try{
                String sqln9 = "SELECT SUM(totalAmount) As sep FROM shop_income WHERE iDate >= '2018/09/01' and iDate <= '2018/09/31' ";
                 pstm9 = con.prepareStatement(sqln9);
                 rsm9 = pstm9.executeQuery(); 
             
        
                 if(rsm9.next()){
        
                         String total = rsm9.getString("sep");
                         System.out.println(total);
            
                         if(total == null){
            
                             septot = 0;
                         }
                          else if(total != null){
                             Double tot = Double.parseDouble(total);
            
                             septot = tot;
                         }
                     }
            
              }catch(SQLException e){}
             
             
             try{
                String sqln10 = "SELECT SUM(totalAmount) As oct FROM shop_income WHERE iDate >= '2018/10/01' and iDate <= '2018/10/31' ";
                 pstm10 = con.prepareStatement(sqln10);
                 rsm10 = pstm10.executeQuery(); 
            
        
                 if(rsm10.next()){
        
                         String total = rsm10.getString("oct");
                         System.out.println(total);
            
                         if(total == null){
            
                             octtot = 0;
                         }
                          else if(total != null){
                             Double tot = Double.parseDouble(total);
            
                             octtot = tot;
                         }
                     }
            
              }catch(SQLException e){}
             
             
             try{
                String sqln11 = "SELECT SUM(totalAmount) As nov FROM shop_income WHERE iDate >= '2018/11/01' and iDate <= '2018/11/31' ";
                 pstm11 = con.prepareStatement(sqln11);
                 rsm11 = pstm11.executeQuery(); 
            
        
                 if(rsm11.next()){
        
                         String total = rsm11.getString("nov");
                         System.out.println(total);
            
                         if(total == null){
            
                             novtot = 0;
                         }
                          else if(total != null){
                             Double tot = Double.parseDouble(total);
            
                             novtot = tot;
                         }
                     }
            
              }catch(SQLException e){}
             
             
             try{
                String sqln12 = "SELECT SUM(totalAmount) As dec FROM shop_income WHERE iDate >= '2018/12/01' and iDate <= '2018/12/31' ";
                 pstm12 = con.prepareStatement(sqln12);
                 rsm12 = pstm12.executeQuery(); 
            
        
                 if(rsm12.next()){
        
                         String total = rsm12.getString("dec");
                         System.out.println(total);
            
                         if(total == null){
            
                             dectot = 0;
                         }
                          else if(total != null){
                             Double tot = Double.parseDouble(total);
            
                             dectot = tot;
                         }
                     }
            
              }catch(SQLException e){}
             
            
            
            
            
            }
         
             
             
             
             
            
        
        
        
        
        //************************************************************************************
        //***********************************************************************************
        
        //................................................
        
       
        
        
        
        
        
        
         DefaultCategoryDataset dcd2 = new DefaultCategoryDataset();
     
        
        dcd2.setValue(jantot,"income","January");
        dcd2.setValue(febtot,"income","February");
        dcd2.setValue(martot,"income","March");
        dcd2.setValue(aprtot,"income","April");
        dcd2.setValue(maytot,"income","May");
        dcd2.setValue(juntot,"income","June");
        dcd2.setValue(jultot,"income","July");
        dcd2.setValue(augtot,"income","August");
        dcd2.setValue(septot,"income","September");
        dcd2.setValue(octtot,"income","October");
        dcd2.setValue(novtot,"income","November");
        dcd2.setValue(dectot,"income","December");
        
         JFreeChart jchart = ChartFactory.createBarChart("Agency Income", "Income Month", "Value Rs.", dcd2, PlotOrientation.VERTICAL, true , true, false);
        
        CategoryPlot plot = jchart.getCategoryPlot();
      
        plot.setBackgroundPaint(new Color(187, 224, 103));
        plot.setRangeGridlinePaint(Color.black);
        
        ChartFrame chartFrm = new ChartFrame("Shop Income",jchart,true);
        chartFrm.setVisible(false);
        chartFrm.setSize(500, 400);
        
        ChartPanel chartPanel = new ChartPanel(jchart);
        
        pnlReport2.removeAll();
        pnlReport2.add(chartPanel);
        pnlReport2.updateUI();
        
        
        
        
        
        
        
        
        
        
    }//GEN-LAST:event_showButActionPerformed

    private void comButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comButActionPerformed
        
        //navigate to compare month income
        CompareMonthIncome m34 = new CompareMonthIncome();
        m34.setVisible(true);
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        m34.setLocation(dim.width/2-this.getSize().width/2,dim.height/2-this.getSize().height/2);
        this.dispose();
        
        
        
    }//GEN-LAST:event_comButActionPerformed

    private void combo4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combo4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        //navigate to mainui
        MainUI a3 = new MainUI();
        a3.setVisible(true);
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        a3.setLocation(dim.width/2-this.getSize().width/2,dim.height/2-this.getSize().height/2);
        this.dispose();
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MonthlySummaryIncome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MonthlySummaryIncome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MonthlySummaryIncome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MonthlySummaryIncome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MonthlySummaryIncome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton comBut;
    private javax.swing.JComboBox<String> combo4;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel pnlReport2;
    private javax.swing.JButton showBut;
    // End of variables declaration//GEN-END:variables

  
    
    private double jantot;
    private double febtot;
    private double martot;
    private double aprtot;
    private double maytot;
    private double juntot;
    private double jultot;
    private double augtot;
    private double septot;
    private double octtot;
    private double novtot;
    private double dectot;

}
