/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fissmda;

import java.awt.Color;
import static java.awt.Color.HSBtoRGB;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.chart.renderer.category.BarRenderer;
import org.jfree.chart.renderer.category.StandardBarPainter;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author Romesh
 */
public class MonthlySummaryUI extends javax.swing.JFrame {
    
    Connection con = null;
    PreparedStatement pst22 = null; 
    ResultSet rs23 = null;
    
    PreparedStatement pst33 = null;
    ResultSet rs24 = null;
    
    PreparedStatement pst44 = null;
    ResultSet rs25 = null;
    
    PreparedStatement pst55 = null;
    ResultSet rs26 = null;
    

    /**
     * Creates new form MonthlySummaryUI
     */
    public MonthlySummaryUI() {
        initComponents();
        
        con = DBConnection.connect();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        showBut = new javax.swing.JButton();
        combo1 = new javax.swing.JComboBox<>();
        pnlReport = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        combo2 = new javax.swing.JComboBox<>();
        vBox = new javax.swing.JLabel();
        wBox = new javax.swing.JLabel();
        pBox = new javax.swing.JLabel();
        sBox = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 91));
        jPanel1.setMaximumSize(new java.awt.Dimension(1276, 815));
        jPanel1.setMinimumSize(new java.awt.Dimension(1276, 815));
        jPanel1.setPreferredSize(new java.awt.Dimension(1276, 815));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fissmda/ButtonImages/monthlysumbanner.png"))); // NOI18N

        showBut.setBackground(new java.awt.Color(204, 245, 75));
        showBut.setText("Show");
        showBut.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        showBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showButActionPerformed(evt);
            }
        });

        combo1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Month", "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));
        combo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo1ActionPerformed(evt);
            }
        });

        pnlReport.setBackground(new java.awt.Color(187, 224, 103));
        pnlReport.setLayout(new javax.swing.BoxLayout(pnlReport, javax.swing.BoxLayout.LINE_AXIS));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fissmda/ButtonImages/homeB.png"))); // NOI18N
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fissmda/ButtonImages/backB.png"))); // NOI18N
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel2.setText("Payments for Manufacturer");

        jLabel3.setText("Warehouse Expences");

        jLabel4.setText("Salary Payments");

        jLabel5.setText("Vehicle Expences");

        combo2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Year", "2017", "2018", " " }));
        combo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo2ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel6.setText("AGENCY  EXPENCES");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("EXPENCES");

        jLabel10.setText("( Right click on the bar chart to see properties [ zoom in | zoom out | print | save as photo ] )");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(210, 210, 210)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(combo2, 0, 166, Short.MAX_VALUE)
                        .addGap(27, 27, 27)
                        .addComponent(combo1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(showBut, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(55, 55, 55)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(vBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(wBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pBox, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sBox, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(33, 33, 33)
                .addComponent(pnlReport, javax.swing.GroupLayout.PREFERRED_SIZE, 813, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(484, 484, 484))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlReport, javax.swing.GroupLayout.PREFERRED_SIZE, 482, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(combo2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(combo1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(showBut, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(74, 74, 74)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(vBox))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(wBox))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pBox))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sBox, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(31, 31, 31)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void showButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showButActionPerformed
        
        
        String month = combo1.getSelectedItem().toString();
        String year = combo2.getSelectedItem().toString();
        
        
        if(month == "Select Month" && year == "Select Year"){
        
            JOptionPane.showMessageDialog(null,"Please select Year and Month ");    
            
        }
        
        else if(month == "Select Month"){
        
            JOptionPane.showMessageDialog(null,"Please select Month.");    
            
        }
        
        else if(year == "Select Year"){
        
            JOptionPane.showMessageDialog(null,"Please select Year.");    
            
        }
    
        
        else if(month == "January" && year == "2017"){
        try{
        String sql = "SELECT SUM(amount) As totAmount FROM vehicle_log WHERE paidDate >= '2017/01/01' and paidDate <= '2017/01/31' ";
        pst22 = con.prepareStatement(sql);
        rs23 = pst22.executeQuery(); 
        System.out.println(month);
        
        if(rs23.next()){
        
            String total = rs23.getString("totAmount");
            System.out.println(total);
            
            if(total == null){
            
                tot1 = 0;
            }
            else if(total != null){
            Double tot = Double.parseDouble(total);
            
            tot1 = tot;
            }
        }
        
        String sql2 = "SELECT SUM(amount) As totAmount2 FROM expenditure WHERE paidDate >= '2017/01/01' and paidDate <= '2017/01/31'" ;
        pst33 = con.prepareStatement(sql2);
        rs24 = pst33.executeQuery();
        
        if(rs24.next()){
        
            String total2 = rs24.getString("totAmount2");
            System.out.println(total2);
            
            if(total2 == null){
            
                tot2 = 0;
            }
            else if(total2 != null){
            Double tot = Double.parseDouble(total2);
            
            tot2 = tot;
            }
            
        }
        
        
        String sql3 = "SELECT SUM(amount) As totAmount3 FROM payment WHERE paidDate >= '2017/01/01' and paidDate <= '2017/01/31'" ;
        pst44 = con.prepareStatement(sql3);
        rs25 = pst44.executeQuery();
        
        if(rs25.next()){
        
            String total3 = rs25.getString("totAmount3");
            System.out.println(total3);
            
            if(total3 == null){
            
                tot3 = 0;
            }
            else if(total3 != null){
            Double tot = Double.parseDouble(total3);
            
            tot3 = tot;
            }
            
        }
        
        String sql4 = "SELECT SUM(salary) As totAmount4 FROM payroll WHERE paidDate >= '2017/01/01' and paidDate <= '2017/01/31'" ;
        pst55 = con.prepareStatement(sql4);
        rs26 = pst55.executeQuery();
        
        if(rs26.next()){
        
            String total4 = rs26.getString("totAmount4");
            System.out.println(total4);
            
            if(total4 == null){
            
                tot4 = 0;
            }
            else if(total4 != null){
            Double tot = Double.parseDouble(total4);
            
            tot4 = tot;
            }
            
        }
        
        
        
        
        
        
        }catch(SQLException e){
        
            
        }
            
        }
        //........................................FEBRUARY.........................................................................
       
        
        else if(month == "February" && year == "2017"){
        try{
        String sql = "SELECT SUM(amount) As totAmount FROM vehicle_log WHERE paidDate >= '2017/02/01' and paidDate <= '2017/02/31' ";
        pst22 = con.prepareStatement(sql);
        rs23 = pst22.executeQuery(); 
        System.out.println(month);
        
        if(rs23.next()){
        
            String total = rs23.getString("totAmount");
            System.out.println(total);
            
            if(total == null){
            
                tot1 = 0;
            }
            else if(total != null){
            Double tot = Double.parseDouble(total);
            
            tot1 = tot;
            }
        }
        
        String sql2 = "SELECT SUM(amount) As totAmount2 FROM expenditure WHERE paidDate >= '2017/02/01' and paidDate <= '2017/02/31'" ;
        pst33 = con.prepareStatement(sql2);
        rs24 = pst33.executeQuery();
        
        if(rs24.next()){
        
            String total2 = rs24.getString("totAmount2");
            System.out.println(total2);
            
            if(total2 == null){
            
                tot2 = 0;
            }
            else if(total2 != null){
            Double tot = Double.parseDouble(total2);
            
            tot2 = tot;
            }
            
        }
        
        
        String sql3 = "SELECT SUM(amount) As totAmount3 FROM payment WHERE paidDate >= '2017/02/01' and paidDate <= '2017/02/31'" ;
        pst44 = con.prepareStatement(sql3);
        rs25 = pst44.executeQuery();
        
        if(rs25.next()){
        
            String total3 = rs25.getString("totAmount3");
            System.out.println(total3);
            
            if(total3 == null){
            
                tot3 = 0;
            }
            else if(total3 != null){
            Double tot = Double.parseDouble(total3);
            
            tot3 = tot;
            }
            
        }
        
        String sql4 = "SELECT SUM(salary) As totAmount4 FROM payroll WHERE paidDate >= '2017/02/01' and paidDate <= '2017/02/31'" ;
        pst55 = con.prepareStatement(sql4);
        rs26 = pst55.executeQuery();
        
        if(rs26.next()){
        
            String total4 = rs26.getString("totAmount4");
            System.out.println(total4);
            
            if(total4 == null){
            
                tot4 = 0;
            }
            else if(total4 != null){
            Double tot = Double.parseDouble(total4);
            
            tot4 = tot;
            }
            
        }
        
        
        
        
        
        
        }catch(SQLException e){
        
            
        }
            
        }
        //.............................march....................................................................
        
        else if(month == "March" && year == "2017"){
        try{
        String sql = "SELECT SUM(amount) As totAmount FROM vehicle_log WHERE paidDate >= '2017/03/01' and paidDate <= '2017/03/31' ";
        pst22 = con.prepareStatement(sql);
        rs23 = pst22.executeQuery(); 
        System.out.println(month);
        
        if(rs23.next()){
        
            String total = rs23.getString("totAmount");
            System.out.println(total);
            
            if(total == null){
            
                tot1 = 0;
            }
            else if(total != null){
            Double tot = Double.parseDouble(total);
            
            tot1 = tot;
            }
        }
        
        String sql2 = "SELECT SUM(amount) As totAmount2 FROM expenditure WHERE paidDate >= '2017/03/01' and paidDate <= '2017/03/31'" ;
        pst33 = con.prepareStatement(sql2);
        rs24 = pst33.executeQuery();
        
        if(rs24.next()){
        
            String total2 = rs24.getString("totAmount2");
            System.out.println(total2);
            
            if(total2 == null){
            
                tot2 = 0;
            }
            else if(total2 != null){
            Double tot = Double.parseDouble(total2);
            
            tot2 = tot;
            }
            
        }
        
        
        String sql3 = "SELECT SUM(amount) As totAmount3 FROM payment WHERE paidDate >= '2017/03/01' and paidDate <= '2017/03/31'" ;
        pst44 = con.prepareStatement(sql3);
        rs25 = pst44.executeQuery();
        
        if(rs25.next()){
        
            String total3 = rs25.getString("totAmount3");
            System.out.println(total3);
            
            if(total3 == null){
            
                tot3 = 0;
            }
            else if(total3 != null){
            Double tot = Double.parseDouble(total3);
            
            tot3 = tot;
            }
            
        }
        
        String sql4 = "SELECT SUM(salary) As totAmount4 FROM payroll WHERE paidDate >= '2017/03/01' and paidDate <= '2017/03/31'" ;
        pst55 = con.prepareStatement(sql4);
        rs26 = pst55.executeQuery();
        
        if(rs26.next()){
        
            String total4 = rs26.getString("totAmount4");
            System.out.println(total4);
            
            if(total4 == null){
            
                tot4 = 0;
            }
            else if(total4 != null){
            Double tot = Double.parseDouble(total4);
            
            tot4 = tot;
            }
            
        }
          
        
        }catch(SQLException e){
        
            
        }
            
        }
       //..........................................April....................................................
       
       
       else if(month == "April" && year == "2017"){
        try{
        String sql = "SELECT SUM(amount) As totAmount FROM vehicle_log WHERE paidDate >= '2017/04/01' and paidDate <= '2017/04/31' ";
        pst22 = con.prepareStatement(sql);
        rs23 = pst22.executeQuery(); 
        System.out.println(month);
        
        if(rs23.next()){
        
            String total = rs23.getString("totAmount");
            System.out.println(total);
            
            if(total == null){
            
                tot1 = 0;
            }
            else if(total != null){
            Double tot = Double.parseDouble(total);
            
            tot1 = tot;
            }
        }
        
        String sql2 = "SELECT SUM(amount) As totAmount2 FROM expenditure WHERE paidDate >= '2017/04/01' and paidDate <= '2017/04/31'" ;
        pst33 = con.prepareStatement(sql2);
        rs24 = pst33.executeQuery();
        
        if(rs24.next()){
        
            String total2 = rs24.getString("totAmount2");
            System.out.println(total2);
            
            if(total2 == null){
            
                tot2 = 0;
            }
            else if(total2 != null){
            Double tot = Double.parseDouble(total2);
            
            tot2 = tot;
            }
            
        }
        
        
        String sql3 = "SELECT SUM(amount) As totAmount3 FROM payment WHERE paidDate >= '2017/04/01' and paidDate <= '2017/04/31'" ;
        pst44 = con.prepareStatement(sql3);
        rs25 = pst44.executeQuery();
        
        if(rs25.next()){
        
            String total3 = rs25.getString("totAmount3");
            System.out.println(total3);
            
            if(total3 == null){
            
                tot3 = 0;
            }
            else if(total3 != null){
            Double tot = Double.parseDouble(total3);
            
            tot3 = tot;
            }
            
        }
        
        String sql4 = "SELECT SUM(salary) As totAmount4 FROM payroll WHERE paidDate >= '2017/04/01' and paidDate <= '2017/04/31'" ;
        pst55 = con.prepareStatement(sql4);
        rs26 = pst55.executeQuery();
        
        if(rs26.next()){
        
            String total4 = rs26.getString("totAmount4");
            System.out.println(total4);
            
            if(total4 == null){
            
                tot4 = 0;
            }
            else if(total4 != null){
            Double tot = Double.parseDouble(total4);
            
            tot4 = tot;
            }
            
        }
          
        
        }catch(SQLException e){
        
            
        }
            
        }
       
      //...................................................May..................................................................... 
       
      
      else if(month == "May" && year == "2017"){
        try{
        String sql = "SELECT SUM(amount) As totAmount FROM vehicle_log WHERE paidDate >= '2017/05/01' and paidDate <= '2017/05/31' ";
        pst22 = con.prepareStatement(sql);
        rs23 = pst22.executeQuery(); 
        System.out.println(month);
        
        if(rs23.next()){
        
            String total = rs23.getString("totAmount");
            System.out.println(total);
            
            if(total == null){
            
                tot1 = 0;
            }
            else if(total != null){
            Double tot = Double.parseDouble(total);
            
            tot1 = tot;
            }
        }
        
        String sql2 = "SELECT SUM(amount) As totAmount2 FROM expenditure WHERE paidDate >= '2017/05/01' and paidDate <= '2017/05/31'" ;
        pst33 = con.prepareStatement(sql2);
        rs24 = pst33.executeQuery();
        
        if(rs24.next()){
        
            String total2 = rs24.getString("totAmount2");
            System.out.println(total2);
            
            if(total2 == null){
            
                tot2 = 0;
            }
            else if(total2 != null){
            Double tot = Double.parseDouble(total2);
            
            tot2 = tot;
            }
            
        }
        
        
        String sql3 = "SELECT SUM(amount) As totAmount3 FROM payment WHERE paidDate >= '2017/05/01' and paidDate <= '2017/05/31'" ;
        pst44 = con.prepareStatement(sql3);
        rs25 = pst44.executeQuery();
        
        if(rs25.next()){
        
            String total3 = rs25.getString("totAmount3");
            System.out.println(total3);
            
            if(total3 == null){
            
                tot3 = 0;
            }
            else if(total3 != null){
            Double tot = Double.parseDouble(total3);
            
            tot3 = tot;
            }
            
        }
        
        String sql4 = "SELECT SUM(salary) As totAmount4 FROM payroll WHERE paidDate >= '2017/05/01' and paidDate <= '2017/05/31'" ;
        pst55 = con.prepareStatement(sql4);
        rs26 = pst55.executeQuery();
        
        if(rs26.next()){
        
            String total4 = rs26.getString("totAmount4");
            System.out.println(total4);
            
            if(total4 == null){
            
                tot4 = 0;
            }
            else if(total4 != null){
            Double tot = Double.parseDouble(total4);
            
            tot4 = tot;
            }
            
        }
          
        
        }catch(SQLException e){
        
            
        }
            
        }
      
      //................................................June.......................................................................
      
      
      else if(month == "July" && year == "2017"){
        try{
        String sql = "SELECT SUM(amount) As totAmount FROM vehicle_log WHERE paidDate >= '2017/06/01' and paidDate <= '2017/06/31' ";
        pst22 = con.prepareStatement(sql);
        rs23 = pst22.executeQuery(); 
        System.out.println(month);
        
        if(rs23.next()){
        
            String total = rs23.getString("totAmount");
            System.out.println(total);
            
            if(total == null){
            
                tot1 = 0;
            }
            else if(total != null){
            Double tot = Double.parseDouble(total);
            
            tot1 = tot;
            }
        }
        
        String sql2 = "SELECT SUM(amount) As totAmount2 FROM expenditure WHERE paidDate >= '2017/06/01' and paidDate <= '2017/06/31'" ;
        pst33 = con.prepareStatement(sql2);
        rs24 = pst33.executeQuery();
        
        if(rs24.next()){
        
            String total2 = rs24.getString("totAmount2");
            System.out.println(total2);
            
            if(total2 == null){
            
                tot2 = 0;
            }
            else if(total2 != null){
            Double tot = Double.parseDouble(total2);
            
            tot2 = tot;
            }
            
        }
        
        
        String sql3 = "SELECT SUM(amount) As totAmount3 FROM payment WHERE paidDate >= '2017/06/01' and paidDate <= '2017/06/31'" ;
        pst44 = con.prepareStatement(sql3);
        rs25 = pst44.executeQuery();
        
        if(rs25.next()){
        
            String total3 = rs25.getString("totAmount3");
            System.out.println(total3);
            
            if(total3 == null){
            
                tot3 = 0;
            }
            else if(total3 != null){
            Double tot = Double.parseDouble(total3);
            
            tot3 = tot;
            }
            
        }
        
        String sql4 = "SELECT SUM(salary) As totAmount4 FROM payroll WHERE paidDate >= '2017/06/01' and paidDate <= '2017/06/31'" ;
        pst55 = con.prepareStatement(sql4);
        rs26 = pst55.executeQuery();
        
        if(rs26.next()){
        
            String total4 = rs26.getString("totAmount4");
            System.out.println(total4);
            
            if(total4 == null){
            
                tot4 = 0;
            }
            else if(total4 != null){
            Double tot = Double.parseDouble(total4);
            
            tot4 = tot;
            }
            
        }
          
        
        }catch(SQLException e){
        
            
        }
            
        }
       
        
      //...............................................July.........................................................................
      
      else if(month == "July" && year == "2017"){
        try{
        String sql = "SELECT SUM(amount) As totAmount FROM vehicle_log WHERE paidDate >= '2017/07/01' and paidDate <= '2017/07/31' ";
        pst22 = con.prepareStatement(sql);
        rs23 = pst22.executeQuery(); 
        System.out.println(month);
        
        if(rs23.next()){
        
            String total = rs23.getString("totAmount");
            System.out.println(total);
            
            if(total == null){
            
                tot1 = 0;
            }
            else if(total != null){
            Double tot = Double.parseDouble(total);
            
            tot1 = tot;
            }
        }
        
        String sql2 = "SELECT SUM(amount) As totAmount2 FROM expenditure WHERE paidDate >= '2017/07/01' and paidDate <= '2017/07/31'" ;
        pst33 = con.prepareStatement(sql2);
        rs24 = pst33.executeQuery();
        
        if(rs24.next()){
        
            String total2 = rs24.getString("totAmount2");
            System.out.println(total2);
            
            if(total2 == null){
            
                tot2 = 0;
            }
            else if(total2 != null){
            Double tot = Double.parseDouble(total2);
            
            tot2 = tot;
            }
            
        }
        
        
        String sql3 = "SELECT SUM(amount) As totAmount3 FROM payment WHERE paidDate >= '2017/07/01' and paidDate <= '2017/07/31'" ;
        pst44 = con.prepareStatement(sql3);
        rs25 = pst44.executeQuery();
        
        if(rs25.next()){
        
            String total3 = rs25.getString("totAmount3");
            System.out.println(total3);
            
            if(total3 == null){
            
                tot3 = 0;
            }
            else if(total3 != null){
            Double tot = Double.parseDouble(total3);
            
            tot3 = tot;
            }
            
        }
        
        String sql4 = "SELECT SUM(salary) As totAmount4 FROM payroll WHERE paidDate >= '2017/07/01' and paidDate <= '2017/07/31'" ;
        pst55 = con.prepareStatement(sql4);
        rs26 = pst55.executeQuery();
        
        if(rs26.next()){
        
            String total4 = rs26.getString("totAmount4");
            System.out.println(total4);
            
            if(total4 == null){
            
                tot4 = 0;
            }
            else if(total4 != null){
            Double tot = Double.parseDouble(total4);
            
            tot4 = tot;
            }
            
        }
          
        
        }catch(SQLException e){
        
            
        }
            
        }
        
        
      //...........................................................August..........................................................
      
      else if(month == "August" && year == "2017"){
        try{
        String sql = "SELECT SUM(amount) As totAmount FROM vehicle_log WHERE paidDate >= '2017/08/01' and paidDate <= '2017/08/31' ";
        pst22 = con.prepareStatement(sql);
        rs23 = pst22.executeQuery(); 
        System.out.println(month);
        
        if(rs23.next()){
        
            String total = rs23.getString("totAmount");
            System.out.println(total);
            
            if(total == null){
            
                tot1 = 0;
            }
            else if(total != null){
            Double tot = Double.parseDouble(total);
            
            tot1 = tot;
            }
        }
        
        String sql2 = "SELECT SUM(amount) As totAmount2 FROM expenditure WHERE paidDate >= '2017/08/01' and paidDate <= '2017/08/31'" ;
        pst33 = con.prepareStatement(sql2);
        rs24 = pst33.executeQuery();
        
        if(rs24.next()){
        
            String total2 = rs24.getString("totAmount2");
            System.out.println(total2);
            
            if(total2 == null){
            
                tot2 = 0;
            }
            else if(total2 != null){
            Double tot = Double.parseDouble(total2);
            
            tot2 = tot;
            }
            
        }
        
        
        String sql3 = "SELECT SUM(amount) As totAmount3 FROM payment WHERE paidDate >= '2017/08/01' and paidDate <= '2017/08/31'" ;
        pst44 = con.prepareStatement(sql3);
        rs25 = pst44.executeQuery();
        
        if(rs25.next()){
        
            String total3 = rs25.getString("totAmount3");
            System.out.println(total3);
            
            if(total3 == null){
            
                tot3 = 0;
            }
            else if(total3 != null){
            Double tot = Double.parseDouble(total3);
            
            tot3 = tot;
            }
            
        }
        
        String sql4 = "SELECT SUM(salary) As totAmount4 FROM payroll WHERE paidDate >= '2017/08/01' and paidDate <= '2017/08/31'" ;
        pst55 = con.prepareStatement(sql4);
        rs26 = pst55.executeQuery();
        
        if(rs26.next()){
        
            String total4 = rs26.getString("totAmount4");
            System.out.println(total4);
            
            if(total4 == null){
            
                tot4 = 0;
            }
            else if(total4 != null){
            Double tot = Double.parseDouble(total4);
            
            tot4 = tot;
            }
            
        }
          
        
        }catch(SQLException e){
        
            
        }
            
        }
        
        
        
        
      //..................................................September...............................................................
      
      else if(month == "September" && year == "2017"){
        try{
        String sql = "SELECT SUM(amount) As totAmount FROM vehicle_log WHERE paidDate >= '2017/09/01' and paidDate <= '2017/09/31' ";
        pst22 = con.prepareStatement(sql);
        rs23 = pst22.executeQuery(); 
        System.out.println(month);
        
        if(rs23.next()){
        
            String total = rs23.getString("totAmount");
            System.out.println(total);
            
            if(total == null){
            
                tot1 = 0;
            }
            else if(total != null){
            Double tot = Double.parseDouble(total);
            
            tot1 = tot;
            }
        }
        
        String sql2 = "SELECT SUM(amount) As totAmount2 FROM expenditure WHERE paidDate >= '2017/09/01' and paidDate <= '2017/09/31'" ;
        pst33 = con.prepareStatement(sql2);
        rs24 = pst33.executeQuery();
        
        if(rs24.next()){
        
            String total2 = rs24.getString("totAmount2");
            System.out.println(total2);
            
            if(total2 == null){
            
                tot2 = 0;
            }
            else if(total2 != null){
            Double tot = Double.parseDouble(total2);
            
            tot2 = tot;
            }
            
        }
        
        
        String sql3 = "SELECT SUM(amount) As totAmount3 FROM payment WHERE paidDate >= '2017/09/01' and paidDate <= '2017/09/31'" ;
        pst44 = con.prepareStatement(sql3);
        rs25 = pst44.executeQuery();
        
        if(rs25.next()){
        
            String total3 = rs25.getString("totAmount3");
            System.out.println(total3);
            
            if(total3 == null){
            
                tot3 = 0;
            }
            else if(total3 != null){
            Double tot = Double.parseDouble(total3);
            
            tot3 = tot;
            }
            
        }
        
        String sql4 = "SELECT SUM(salary) As totAmount4 FROM payroll WHERE paidDate >= '2017/09/01' and paidDate <= '2017/09/31'" ;
        pst55 = con.prepareStatement(sql4);
        rs26 = pst55.executeQuery();
        
        if(rs26.next()){
        
            String total4 = rs26.getString("totAmount4");
            System.out.println(total4);
            
            if(total4 == null){
            
                tot4 = 0;
            }
            else if(total4 != null){
            Double tot = Double.parseDouble(total4);
            
            tot4 = tot;
            }
            
        }
          
        
        }catch(SQLException e){
        
            
        }
            
        }
        
      //.................................................October....................................................................
      
      else if(month == "October" && year == "2017"){
        try{
        String sql = "SELECT SUM(amount) As totAmount FROM vehicle_log WHERE paidDate >= '2017/10/01' and paidDate <= '2017/10/31' ";
        pst22 = con.prepareStatement(sql);
        rs23 = pst22.executeQuery(); 
        System.out.println(month);
        
        if(rs23.next()){
        
            String total = rs23.getString("totAmount");
            System.out.println(total);
            
            if(total == null){
            
                tot1 = 0;
            }
            else if(total != null){
            Double tot = Double.parseDouble(total);
            
            tot1 = tot;
            }
        }
        
        String sql2 = "SELECT SUM(amount) As totAmount2 FROM expenditure WHERE paidDate >= '2017/10/01' and paidDate <= '2017/10/31'" ;
        pst33 = con.prepareStatement(sql2);
        rs24 = pst33.executeQuery();
        
        if(rs24.next()){
        
            String total2 = rs24.getString("totAmount2");
            System.out.println(total2);
            
            if(total2 == null){
            
                tot2 = 0;
            }
            else if(total2 != null){
            Double tot = Double.parseDouble(total2);
            
            tot2 = tot;
            }
            
        }
        
        
        String sql3 = "SELECT SUM(amount) As totAmount3 FROM payment WHERE paidDate >= '2017/10/01' and paidDate <= '2017/10/31'" ;
        pst44 = con.prepareStatement(sql3);
        rs25 = pst44.executeQuery();
        
        if(rs25.next()){
        
            String total3 = rs25.getString("totAmount3");
            System.out.println(total3);
            
            if(total3 == null){
            
                tot3 = 0;
            }
            else if(total3 != null){
            Double tot = Double.parseDouble(total3);
            
            tot3 = tot;
            }
            
        }
        
        String sql4 = "SELECT SUM(salary) As totAmount4 FROM payroll WHERE paidDate >= '2017/10/01' and paidDate <= '2017/10/31'" ;
        pst55 = con.prepareStatement(sql4);
        rs26 = pst55.executeQuery();
        
        if(rs26.next()){
        
            String total4 = rs26.getString("totAmount4");
            System.out.println(total4);
            
            if(total4 == null){
            
                tot4 = 0;
            }
            else if(total4 != null){
            Double tot = Double.parseDouble(total4);
            
            tot4 = tot;
            }
            
        }
          
        
        }catch(SQLException e){
        
            
        }
            
        }
        
        
      //...........................................November........................................................................
      
      else if(month == "November" && year == "2017"){
        try{
        String sql = "SELECT SUM(amount) As totAmount FROM vehicle_log WHERE paidDate >= '2017/11/01' and paidDate <= '2017/11/31' ";
        pst22 = con.prepareStatement(sql);
        rs23 = pst22.executeQuery(); 
        System.out.println(month);
        
        if(rs23.next()){
        
            String total = rs23.getString("totAmount");
            System.out.println(total);
            
            if(total == null){
            
                tot1 = 0;
            }
            else if(total != null){
            Double tot = Double.parseDouble(total);
            
            tot1 = tot;
            }
        }
        
        String sql2 = "SELECT SUM(amount) As totAmount2 FROM expenditure WHERE paidDate >= '2017/11/01' and paidDate <= '2017/11/31'" ;
        pst33 = con.prepareStatement(sql2);
        rs24 = pst33.executeQuery();
        
        if(rs24.next()){
        
            String total2 = rs24.getString("totAmount2");
            System.out.println(total2);
            
            if(total2 == null){
            
                tot2 = 0;
            }
            else if(total2 != null){
            Double tot = Double.parseDouble(total2);
            
            tot2 = tot;
            }
            
        }
        
        
        String sql3 = "SELECT SUM(amount) As totAmount3 FROM payment WHERE paidDate >= '2017/11/01' and paidDate <= '2017/11/31'" ;
        pst44 = con.prepareStatement(sql3);
        rs25 = pst44.executeQuery();
        
        if(rs25.next()){
        
            String total3 = rs25.getString("totAmount3");
            System.out.println(total3);
            
            if(total3 == null){
            
                tot3 = 0;
            }
            else if(total3 != null){
            Double tot = Double.parseDouble(total3);
            
            tot3 = tot;
            }
            
        }
        
        String sql4 = "SELECT SUM(salary) As totAmount4 FROM payroll WHERE paidDate >= '2017/11/01' and paidDate <= '2017/11/31'" ;
        pst55 = con.prepareStatement(sql4);
        rs26 = pst55.executeQuery();
        
        if(rs26.next()){
        
            String total4 = rs26.getString("totAmount4");
            System.out.println(total4);
            
            if(total4 == null){
            
                tot4 = 0;
            }
            else if(total4 != null){
            Double tot = Double.parseDouble(total4);
            
            tot4 = tot;
            }
            
        }
          
        
        }catch(SQLException e){
        
            
        }
            
        }
        
      //.......................................................December.............................................................
      
      else if(month == "December" && year == "2017"){
        try{
        String sql = "SELECT SUM(amount) As totAmount FROM vehicle_log WHERE paidDate >= '2017/12/01' and paidDate <= '2017/12/31' ";
        pst22 = con.prepareStatement(sql);
        rs23 = pst22.executeQuery(); 
        System.out.println(month);
        
        if(rs23.next()){
        
            String total = rs23.getString("totAmount");
            System.out.println(total);
            
            if(total == null){
            
                tot1 = 0;
            }
            else if(total != null){
            Double tot = Double.parseDouble(total);
            
            tot1 = tot;
            }
        }
        
        String sql2 = "SELECT SUM(amount) As totAmount2 FROM expenditure WHERE paidDate >= '2017/12/01' and paidDate <= '2017/12/31'" ;
        pst33 = con.prepareStatement(sql2);
        rs24 = pst33.executeQuery();
        
        if(rs24.next()){
        
            String total2 = rs24.getString("totAmount2");
            System.out.println(total2);
            
            if(total2 == null){
            
                tot2 = 0;
            }
            else if(total2 != null){
            Double tot = Double.parseDouble(total2);
            
            tot2 = tot;
            }
            
        }
        
        
        String sql3 = "SELECT SUM(amount) As totAmount3 FROM payment WHERE paidDate >= '2017/12/01' and paidDate <= '2017/12/31'" ;
        pst44 = con.prepareStatement(sql3);
        rs25 = pst44.executeQuery();
        
        if(rs25.next()){
        
            String total3 = rs25.getString("totAmount3");
            System.out.println(total3);
            
            if(total3 == null){
            
                tot3 = 0;
            }
            else if(total3 != null){
            Double tot = Double.parseDouble(total3);
            
            tot3 = tot;
            }
            
        }
        
        String sql4 = "SELECT SUM(salary) As totAmount4 FROM payroll WHERE paidDate >= '2017/12/01' and paidDate <= '2017/12/31'" ;
        pst55 = con.prepareStatement(sql4);
        rs26 = pst55.executeQuery();
        
        if(rs26.next()){
        
            String total4 = rs26.getString("totAmount4");
            System.out.println(total4);
            
            if(total4 == null){
            
                tot4 = 0;
            }
            else if(total4 != null){
            Double tot = Double.parseDouble(total4);
            
            tot4 = tot;
            }
            
        }
          
        
        }catch(SQLException e){
        
            
        }
            
        }
        
      //********************************************************2018****************************************************************
      //***************************************************************************************************************************
      
      else if(month == "January" && year == "2018"){
          
          try{
        String sql = "SELECT SUM(amount) As totAmount FROM vehicle_log WHERE paidDate >= '2018/01/01' and paidDate <= '2018/01/31' ";
        pst22 = con.prepareStatement(sql);
        rs23 = pst22.executeQuery(); 
        System.out.println(month);
        
        if(rs23.next()){
        
            String total = rs23.getString("totAmount");
            System.out.println(total);
            
            if(total == null){
            
                tot1 = 0;
            }
            else if(total != null){
            Double tot = Double.parseDouble(total);
            
            tot1 = tot;
            }
        }
        
        String sql2 = "SELECT SUM(amount) As totAmount2 FROM expenditure WHERE paidDate >= '2018/01/01' and paidDate <= '2018/01/31'" ;
        pst33 = con.prepareStatement(sql2);
        rs24 = pst33.executeQuery();
        
        if(rs24.next()){
        
            String total2 = rs24.getString("totAmount2");
            System.out.println(total2);
            
            if(total2 == null){
            
                tot2 = 0;
            }
            else if(total2 != null){
            Double tot = Double.parseDouble(total2);
            
            tot2 = tot;
            }
            
        }
        
        
        String sql3 = "SELECT SUM(amount) As totAmount3 FROM payment WHERE paidDate >= '2018/01/01' and paidDate <= '2018/01/31'" ;
        pst44 = con.prepareStatement(sql3);
        rs25 = pst44.executeQuery();
        
        if(rs25.next()){
        
            String total3 = rs25.getString("totAmount3");
            System.out.println(total3);
            
            if(total3 == null){
            
                tot3 = 0;
            }
            else if(total3 != null){
            Double tot = Double.parseDouble(total3);
            
            tot3 = tot;
            }
            
        }
        
        String sql4 = "SELECT SUM(salary) As totAmount4 FROM payroll WHERE paidDate >= '2018/01/01' and paidDate <= '2018/01/31'" ;
        pst55 = con.prepareStatement(sql4);
        rs26 = pst55.executeQuery();
        
        if(rs26.next()){
        
            String total4 = rs26.getString("totAmount4");
            System.out.println(total4);
            
            if(total4 == null){
            
                tot4 = 0;
            }
            else if(total4 != null){
            Double tot = Double.parseDouble(total4);
            
            tot4 = tot;
            }
            
        }
        
        
        
        
        
        
        }catch(SQLException e){
        
            
        }
      
          
      }
        
     
     //........................................FEBRUARY.........................................................................
       
        
        else if(month == "February" && year == "2018"){
        try{
        String sql = "SELECT SUM(amount) As totAmount FROM vehicle_log WHERE paidDate >= '2018/02/01' and paidDate <= '2018/02/31' ";
        pst22 = con.prepareStatement(sql);
        rs23 = pst22.executeQuery(); 
        System.out.println(month);
        
        if(rs23.next()){
        
            String total = rs23.getString("totAmount");
            System.out.println(total);
            
            if(total == null){
            
                tot1 = 0;
            }
            else if(total != null){
            Double tot = Double.parseDouble(total);
            
            tot1 = tot;
            }
        }
        
        String sql2 = "SELECT SUM(amount) As totAmount2 FROM expenditure WHERE paidDate >= '2018/02/01' and paidDate <= '2018/02/31'" ;
        pst33 = con.prepareStatement(sql2);
        rs24 = pst33.executeQuery();
        
        if(rs24.next()){
        
            String total2 = rs24.getString("totAmount2");
            System.out.println(total2);
            
            if(total2 == null){
            
                tot2 = 0;
            }
            else if(total2 != null){
            Double tot = Double.parseDouble(total2);
            
            tot2 = tot;
            }
            
        }
        
        
        String sql3 = "SELECT SUM(amount) As totAmount3 FROM payment WHERE paidDate >= '2018/02/01' and paidDate <= '2018/02/31'" ;
        pst44 = con.prepareStatement(sql3);
        rs25 = pst44.executeQuery();
        
        if(rs25.next()){
        
            String total3 = rs25.getString("totAmount3");
            System.out.println(total3);
            
            if(total3 == null){
            
                tot3 = 0;
            }
            else if(total3 != null){
            Double tot = Double.parseDouble(total3);
            
            tot3 = tot;
            }
            
        }
        
        String sql4 = "SELECT SUM(salary) As totAmount4 FROM payroll WHERE paidDate >= '2018/02/01' and paidDate <= '2018/02/31'" ;
        pst55 = con.prepareStatement(sql4);
        rs26 = pst55.executeQuery();
        
        if(rs26.next()){
        
            String total4 = rs26.getString("totAmount4");
            System.out.println(total4);
            
            if(total4 == null){
            
                tot4 = 0;
            }
            else if(total4 != null){
            Double tot = Double.parseDouble(total4);
            
            tot4 = tot;
            }
            
        }
        
        
        
        
        
        
        }catch(SQLException e){
        
            
        }
            
        }
        //.............................march....................................................................
        
        else if(month == "March" && year == "2018"){
        try{
        String sql = "SELECT SUM(amount) As totAmount FROM vehicle_log WHERE paidDate >= '2018/03/01' and paidDate <= '2018/03/31' ";
        pst22 = con.prepareStatement(sql);
        rs23 = pst22.executeQuery(); 
        System.out.println(month);
        
        if(rs23.next()){
        
            String total = rs23.getString("totAmount");
            System.out.println(total);
            
            if(total == null){
            
                tot1 = 0;
            }
            else if(total != null){
            Double tot = Double.parseDouble(total);
            
            tot1 = tot;
            }
        }
        
        String sql2 = "SELECT SUM(amount) As totAmount2 FROM expenditure WHERE paidDate >= '2018/03/01' and paidDate <= '2018/03/31'" ;
        pst33 = con.prepareStatement(sql2);
        rs24 = pst33.executeQuery();
        
        if(rs24.next()){
        
            String total2 = rs24.getString("totAmount2");
            System.out.println(total2);
            
            if(total2 == null){
            
                tot2 = 0;
            }
            else if(total2 != null){
            Double tot = Double.parseDouble(total2);
            
            tot2 = tot;
            }
            
        }
        
        
        String sql3 = "SELECT SUM(amount) As totAmount3 FROM payment WHERE paidDate >= '2018/03/01' and paidDate <= '2018/03/31'" ;
        pst44 = con.prepareStatement(sql3);
        rs25 = pst44.executeQuery();
        
        if(rs25.next()){
        
            String total3 = rs25.getString("totAmount3");
            System.out.println(total3);
            
            if(total3 == null){
            
                tot3 = 0;
            }
            else if(total3 != null){
            Double tot = Double.parseDouble(total3);
            
            tot3 = tot;
            }
            
        }
        
        String sql4 = "SELECT SUM(salary) As totAmount4 FROM payroll WHERE paidDate >= '2018/03/01' and paidDate <= '2018/03/31'" ;
        pst55 = con.prepareStatement(sql4);
        rs26 = pst55.executeQuery();
        
        if(rs26.next()){
        
            String total4 = rs26.getString("totAmount4");
            System.out.println(total4);
            
            if(total4 == null){
            
                tot4 = 0;
            }
            else if(total4 != null){
            Double tot = Double.parseDouble(total4);
            
            tot4 = tot;
            }
            
        }
          
        
        }catch(SQLException e){
        
            
        }
            
        }
       //..........................................April....................................................
       
       
       else if(month == "April" && year == "2018"){
        try{
        String sql = "SELECT SUM(amount) As totAmount FROM vehicle_log WHERE paidDate >= '2018/04/01' and paidDate <= '2018/04/31' ";
        pst22 = con.prepareStatement(sql);
        rs23 = pst22.executeQuery(); 
        System.out.println(month);
        
        if(rs23.next()){
        
            String total = rs23.getString("totAmount");
            System.out.println(total);
            
            if(total == null){
            
                tot1 = 0;
            }
            else if(total != null){
            Double tot = Double.parseDouble(total);
            
            tot1 = tot;
            }
        }
        
        String sql2 = "SELECT SUM(amount) As totAmount2 FROM expenditure WHERE paidDate >= '2018/04/01' and paidDate <= '2018/04/31'" ;
        pst33 = con.prepareStatement(sql2);
        rs24 = pst33.executeQuery();
        
        if(rs24.next()){
        
            String total2 = rs24.getString("totAmount2");
            System.out.println(total2);
            
            if(total2 == null){
            
                tot2 = 0;
            }
            else if(total2 != null){
            Double tot = Double.parseDouble(total2);
            
            tot2 = tot;
            }
            
        }
        
        
        String sql3 = "SELECT SUM(amount) As totAmount3 FROM payment WHERE paidDate >= '2018/04/01' and paidDate <= '2018/04/31'" ;
        pst44 = con.prepareStatement(sql3);
        rs25 = pst44.executeQuery();
        
        if(rs25.next()){
        
            String total3 = rs25.getString("totAmount3");
            System.out.println(total3);
            
            if(total3 == null){
            
                tot3 = 0;
            }
            else if(total3 != null){
            Double tot = Double.parseDouble(total3);
            
            tot3 = tot;
            }
            
        }
        
        String sql4 = "SELECT SUM(salary) As totAmount4 FROM payroll WHERE paidDate >= '2018/04/01' and paidDate <= '2018/04/31'" ;
        pst55 = con.prepareStatement(sql4);
        rs26 = pst55.executeQuery();
        
        if(rs26.next()){
        
            String total4 = rs26.getString("totAmount4");
            System.out.println(total4);
            
            if(total4 == null){
            
                tot4 = 0;
            }
            else if(total4 != null){
            Double tot = Double.parseDouble(total4);
            
            tot4 = tot;
            }
            
        }
          
        
        }catch(SQLException e){
        
            
        }
            
        }
       
      //...................................................May..................................................................... 
       
      
      else if(month == "May" && year == "2018"){
        try{
        String sql = "SELECT SUM(amount) As totAmount FROM vehicle_log WHERE paidDate >= '2018/05/01' and paidDate <= '2018/05/31' ";
        pst22 = con.prepareStatement(sql);
        rs23 = pst22.executeQuery(); 
        System.out.println(month);
        
        if(rs23.next()){
        
            String total = rs23.getString("totAmount");
            System.out.println(total);
            
            if(total == null){
            
                tot1 = 0;
            }
            else if(total != null){
            Double tot = Double.parseDouble(total);
            
            tot1 = tot;
            }
        }
        
        String sql2 = "SELECT SUM(amount) As totAmount2 FROM expenditure WHERE paidDate >= '2018/05/01' and paidDate <= '2018/05/31'" ;
        pst33 = con.prepareStatement(sql2);
        rs24 = pst33.executeQuery();
        
        if(rs24.next()){
        
            String total2 = rs24.getString("totAmount2");
            System.out.println(total2);
            
            if(total2 == null){
            
                tot2 = 0;
            }
            else if(total2 != null){
            Double tot = Double.parseDouble(total2);
            
            tot2 = tot;
            }
            
        }
        
        
        String sql3 = "SELECT SUM(amount) As totAmount3 FROM payment WHERE paidDate >= '2018/05/01' and paidDate <= '2018/05/31'" ;
        pst44 = con.prepareStatement(sql3);
        rs25 = pst44.executeQuery();
        
        if(rs25.next()){
        
            String total3 = rs25.getString("totAmount3");
            System.out.println(total3);
            
            if(total3 == null){
            
                tot3 = 0;
            }
            else if(total3 != null){
            Double tot = Double.parseDouble(total3);
            
            tot3 = tot;
            }
            
        }
        
        String sql4 = "SELECT SUM(salary) As totAmount4 FROM payroll WHERE paidDate >= '2018/05/01' and paidDate <= '2018/05/31'" ;
        pst55 = con.prepareStatement(sql4);
        rs26 = pst55.executeQuery();
        
        if(rs26.next()){
        
            String total4 = rs26.getString("totAmount4");
            System.out.println(total4);
            
            if(total4 == null){
            
                tot4 = 0;
            }
            else if(total4 != null){
            Double tot = Double.parseDouble(total4);
            
            tot4 = tot;
            }
            
        }
          
        
        }catch(SQLException e){
        
            
        }
            
        }
      
      //................................................June.......................................................................
      
      
      else if(month == "July" && year == "2018"){
        try{
        String sql = "SELECT SUM(amount) As totAmount FROM vehicle_log WHERE paidDate >= '2018/06/01' and paidDate <= '2018/06/31' ";
        pst22 = con.prepareStatement(sql);
        rs23 = pst22.executeQuery(); 
        System.out.println(month);
        
        if(rs23.next()){
        
            String total = rs23.getString("totAmount");
            System.out.println(total);
            
            if(total == null){
            
                tot1 = 0;
            }
            else if(total != null){
            Double tot = Double.parseDouble(total);
            
            tot1 = tot;
            }
        }
        
        String sql2 = "SELECT SUM(amount) As totAmount2 FROM expenditure WHERE paidDate >= '2018/06/01' and paidDate <= '2018/06/31'" ;
        pst33 = con.prepareStatement(sql2);
        rs24 = pst33.executeQuery();
        
        if(rs24.next()){
        
            String total2 = rs24.getString("totAmount2");
            System.out.println(total2);
            
            if(total2 == null){
            
                tot2 = 0;
            }
            else if(total2 != null){
            Double tot = Double.parseDouble(total2);
            
            tot2 = tot;
            }
            
        }
        
        
        String sql3 = "SELECT SUM(amount) As totAmount3 FROM payment WHERE paidDate >= '2018/06/01' and paidDate <= '2018/06/31'" ;
        pst44 = con.prepareStatement(sql3);
        rs25 = pst44.executeQuery();
        
        if(rs25.next()){
        
            String total3 = rs25.getString("totAmount3");
            System.out.println(total3);
            
            if(total3 == null){
            
                tot3 = 0;
            }
            else if(total3 != null){
            Double tot = Double.parseDouble(total3);
            
            tot3 = tot;
            }
            
        }
        
        String sql4 = "SELECT SUM(salary) As totAmount4 FROM payroll WHERE paidDate >= '2018/06/01' and paidDate <= '2018/06/31'" ;
        pst55 = con.prepareStatement(sql4);
        rs26 = pst55.executeQuery();
        
        if(rs26.next()){
        
            String total4 = rs26.getString("totAmount4");
            System.out.println(total4);
            
            if(total4 == null){
            
                tot4 = 0;
            }
            else if(total4 != null){
            Double tot = Double.parseDouble(total4);
            
            tot4 = tot;
            }
            
        }
          
        
        }catch(SQLException e){
        
            
        }
            
        }
       
        
      //...............................................July.........................................................................
      
      else if(month == "July" && year == "2018"){
        try{
        String sql = "SELECT SUM(amount) As totAmount FROM vehicle_log WHERE paidDate >= '2018/07/01' and paidDate <= '2018/07/31' ";
        pst22 = con.prepareStatement(sql);
        rs23 = pst22.executeQuery(); 
        System.out.println(month);
        
        if(rs23.next()){
        
            String total = rs23.getString("totAmount");
            System.out.println(total);
            
            if(total == null){
            
                tot1 = 0;
            }
            else if(total != null){
            Double tot = Double.parseDouble(total);
            
            tot1 = tot;
            }
        }
        
        String sql2 = "SELECT SUM(amount) As totAmount2 FROM expenditure WHERE paidDate >= '2018/07/01' and paidDate <= '2018/07/31'" ;
        pst33 = con.prepareStatement(sql2);
        rs24 = pst33.executeQuery();
        
        if(rs24.next()){
        
            String total2 = rs24.getString("totAmount2");
            System.out.println(total2);
            
            if(total2 == null){
            
                tot2 = 0;
            }
            else if(total2 != null){
            Double tot = Double.parseDouble(total2);
            
            tot2 = tot;
            }
            
        }
        
        
        String sql3 = "SELECT SUM(amount) As totAmount3 FROM payment WHERE paidDate >= '2018/07/01' and paidDate <= '2018/07/31'" ;
        pst44 = con.prepareStatement(sql3);
        rs25 = pst44.executeQuery();
        
        if(rs25.next()){
        
            String total3 = rs25.getString("totAmount3");
            System.out.println(total3);
            
            if(total3 == null){
            
                tot3 = 0;
            }
            else if(total3 != null){
            Double tot = Double.parseDouble(total3);
            
            tot3 = tot;
            }
            
        }
        
        String sql4 = "SELECT SUM(salary) As totAmount4 FROM payroll WHERE paidDate >= '2018/07/01' and paidDate <= '2018/07/31'" ;
        pst55 = con.prepareStatement(sql4);
        rs26 = pst55.executeQuery();
        
        if(rs26.next()){
        
            String total4 = rs26.getString("totAmount4");
            System.out.println(total4);
            
            if(total4 == null){
            
                tot4 = 0;
            }
            else if(total4 != null){
            Double tot = Double.parseDouble(total4);
            
            tot4 = tot;
            }
            
        }
          
        
        }catch(SQLException e){
        
            
        }
            
        }
        
        
      //...........................................................August..........................................................
      
      else if(month == "August" && year == "2018"){
        try{
        String sql = "SELECT SUM(amount) As totAmount FROM vehicle_log WHERE paidDate >= '2018/08/01' and paidDate <= '2018/08/31' ";
        pst22 = con.prepareStatement(sql);
        rs23 = pst22.executeQuery(); 
        System.out.println(month);
        
        if(rs23.next()){
        
            String total = rs23.getString("totAmount");
            System.out.println(total);
            
            if(total == null){
            
                tot1 = 0;
            }
            else if(total != null){
            Double tot = Double.parseDouble(total);
            
            tot1 = tot;
            }
        }
        
        String sql2 = "SELECT SUM(amount) As totAmount2 FROM expenditure WHERE paidDate >= '2018/08/01' and paidDate <= '2018/08/31'" ;
        pst33 = con.prepareStatement(sql2);
        rs24 = pst33.executeQuery();
        
        if(rs24.next()){
        
            String total2 = rs24.getString("totAmount2");
            System.out.println(total2);
            
            if(total2 == null){
            
                tot2 = 0;
            }
            else if(total2 != null){
            Double tot = Double.parseDouble(total2);
            
            tot2 = tot;
            }
            
        }
        
        
        String sql3 = "SELECT SUM(amount) As totAmount3 FROM payment WHERE paidDate >= '2018/08/01' and paidDate <= '2018/08/31'" ;
        pst44 = con.prepareStatement(sql3);
        rs25 = pst44.executeQuery();
        
        if(rs25.next()){
        
            String total3 = rs25.getString("totAmount3");
            System.out.println(total3);
            
            if(total3 == null){
            
                tot3 = 0;
            }
            else if(total3 != null){
            Double tot = Double.parseDouble(total3);
            
            tot3 = tot;
            }
            
        }
        
        String sql4 = "SELECT SUM(salary) As totAmount4 FROM payroll WHERE paidDate >= '2018/08/01' and paidDate <= '2018/08/31'" ;
        pst55 = con.prepareStatement(sql4);
        rs26 = pst55.executeQuery();
        
        if(rs26.next()){
        
            String total4 = rs26.getString("totAmount4");
            System.out.println(total4);
            
            if(total4 == null){
            
                tot4 = 0;
            }
            else if(total4 != null){
            Double tot = Double.parseDouble(total4);
            
            tot4 = tot;
            }
            
        }
          
        
        }catch(SQLException e){
        
            
        }
            
        }
        
        
        
        
      //..................................................September...............................................................
      
      else if(month == "September" && year == "2018"){
        try{
        String sql = "SELECT SUM(amount) As totAmount FROM vehicle_log WHERE paidDate >= '2018/09/01' and paidDate <= '2018/09/31' ";
        pst22 = con.prepareStatement(sql);
        rs23 = pst22.executeQuery(); 
        System.out.println(month);
        
        if(rs23.next()){
        
            String total = rs23.getString("totAmount");
            System.out.println(total);
            
            if(total == null){
            
                tot1 = 0;
            }
            else if(total != null){
            Double tot = Double.parseDouble(total);
            
            tot1 = tot;
            }
        }
        
        String sql2 = "SELECT SUM(amount) As totAmount2 FROM expenditure WHERE paidDate >= '2018/09/01' and paidDate <= '2018/09/31'" ;
        pst33 = con.prepareStatement(sql2);
        rs24 = pst33.executeQuery();
        
        if(rs24.next()){
        
            String total2 = rs24.getString("totAmount2");
            System.out.println(total2);
            
            if(total2 == null){
            
                tot2 = 0;
            }
            else if(total2 != null){
            Double tot = Double.parseDouble(total2);
            
            tot2 = tot;
            }
            
        }
        
        
        String sql3 = "SELECT SUM(amount) As totAmount3 FROM payment WHERE paidDate >= '2018/09/01' and paidDate <= '2018/09/31'" ;
        pst44 = con.prepareStatement(sql3);
        rs25 = pst44.executeQuery();
        
        if(rs25.next()){
        
            String total3 = rs25.getString("totAmount3");
            System.out.println(total3);
            
            if(total3 == null){
            
                tot3 = 0;
            }
            else if(total3 != null){
            Double tot = Double.parseDouble(total3);
            
            tot3 = tot;
            }
            
        }
        
        String sql4 = "SELECT SUM(salary) As totAmount4 FROM payroll WHERE paidDate >= '2018/09/01' and paidDate <= '2018/09/31'" ;
        pst55 = con.prepareStatement(sql4);
        rs26 = pst55.executeQuery();
        
        if(rs26.next()){
        
            String total4 = rs26.getString("totAmount4");
            System.out.println(total4);
            
            if(total4 == null){
            
                tot4 = 0;
            }
            else if(total4 != null){
            Double tot = Double.parseDouble(total4);
            
            tot4 = tot;
            }
            
        }
          
        
        }catch(SQLException e){
        
            
        }
            
        }
        
      //.................................................October....................................................................
      
      else if(month == "October" && year == "2018"){
        try{
        String sql = "SELECT SUM(amount) As totAmount FROM vehicle_log WHERE paidDate >= '2018/10/01' and paidDate <= '2018/10/31' ";
        pst22 = con.prepareStatement(sql);
        rs23 = pst22.executeQuery(); 
        System.out.println(month);
        
        if(rs23.next()){
        
            String total = rs23.getString("totAmount");
            System.out.println(total);
            
            if(total == null){
            
                tot1 = 0;
            }
            else if(total != null){
            Double tot = Double.parseDouble(total);
            
            tot1 = tot;
            }
        }
        
        String sql2 = "SELECT SUM(amount) As totAmount2 FROM expenditure WHERE paidDate >= '2018/10/01' and paidDate <= '2018/10/31'" ;
        pst33 = con.prepareStatement(sql2);
        rs24 = pst33.executeQuery();
        
        if(rs24.next()){
        
            String total2 = rs24.getString("totAmount2");
            System.out.println(total2);
            
            if(total2 == null){
            
                tot2 = 0;
            }
            else if(total2 != null){
            Double tot = Double.parseDouble(total2);
            
            tot2 = tot;
            }
            
        }
        
        
        String sql3 = "SELECT SUM(amount) As totAmount3 FROM payment WHERE paidDate >= '2018/10/01' and paidDate <= '2018/10/31'" ;
        pst44 = con.prepareStatement(sql3);
        rs25 = pst44.executeQuery();
        
        if(rs25.next()){
        
            String total3 = rs25.getString("totAmount3");
            System.out.println(total3);
            
            if(total3 == null){
            
                tot3 = 0;
            }
            else if(total3 != null){
            Double tot = Double.parseDouble(total3);
            
            tot3 = tot;
            }
            
        }
        
        String sql4 = "SELECT SUM(salary) As totAmount4 FROM payroll WHERE paidDate >= '2018/10/01' and paidDate <= '2018/10/31'" ;
        pst55 = con.prepareStatement(sql4);
        rs26 = pst55.executeQuery();
        
        if(rs26.next()){
        
            String total4 = rs26.getString("totAmount4");
            System.out.println(total4);
            
            if(total4 == null){
            
                tot4 = 0;
            }
            else if(total4 != null){
            Double tot = Double.parseDouble(total4);
            
            tot4 = tot;
            }
            
        }
          
        
        }catch(SQLException e){
        
            
        }
            
        }
        
        
      //...........................................November........................................................................
      
      else if(month == "November" && year == "2018"){
        try{
        String sql = "SELECT SUM(amount) As totAmount FROM vehicle_log WHERE paidDate >= '2018/11/01' and paidDate <= '2018/11/31' ";
        pst22 = con.prepareStatement(sql);
        rs23 = pst22.executeQuery(); 
        System.out.println(month);
        
        if(rs23.next()){
        
            String total = rs23.getString("totAmount");
            System.out.println(total);
            
            if(total == null){
            
                tot1 = 0;
            }
            else if(total != null){
            Double tot = Double.parseDouble(total);
            
            tot1 = tot;
            }
        }
        
        String sql2 = "SELECT SUM(amount) As totAmount2 FROM expenditure WHERE paidDate >= '2018/11/01' and paidDate <= '2018/11/31'" ;
        pst33 = con.prepareStatement(sql2);
        rs24 = pst33.executeQuery();
        
        if(rs24.next()){
        
            String total2 = rs24.getString("totAmount2");
            System.out.println(total2);
            
            if(total2 == null){
            
                tot2 = 0;
            }
            else if(total2 != null){
            Double tot = Double.parseDouble(total2);
            
            tot2 = tot;
            }
            
        }
        
        
        String sql3 = "SELECT SUM(amount) As totAmount3 FROM payment WHERE paidDate >= '2018/11/01' and paidDate <= '2018/11/31'" ;
        pst44 = con.prepareStatement(sql3);
        rs25 = pst44.executeQuery();
        
        if(rs25.next()){
        
            String total3 = rs25.getString("totAmount3");
            System.out.println(total3);
            
            if(total3 == null){
            
                tot3 = 0;
            }
            else if(total3 != null){
            Double tot = Double.parseDouble(total3);
            
            tot3 = tot;
            }
            
        }
        
        String sql4 = "SELECT SUM(salary) As totAmount4 FROM payroll WHERE paidDate >= '2018/11/01' and paidDate <= '2018/11/31'" ;
        pst55 = con.prepareStatement(sql4);
        rs26 = pst55.executeQuery();
        
        if(rs26.next()){
        
            String total4 = rs26.getString("totAmount4");
            System.out.println(total4);
            
            if(total4 == null){
            
                tot4 = 0;
            }
            else if(total4 != null){
            Double tot = Double.parseDouble(total4);
            
            tot4 = tot;
            }
            
        }
          
        
        }catch(SQLException e){
        
            
        }
            
        }
        
      //.......................................................December.............................................................
      
      else if(month == "December" && year == "2018"){
        try{
        String sql = "SELECT SUM(amount) As totAmount FROM vehicle_log WHERE paidDate >= '2018/12/01' and paidDate <= '2018/12/31' ";
        pst22 = con.prepareStatement(sql);
        rs23 = pst22.executeQuery(); 
        System.out.println(month);
        
        if(rs23.next()){
        
            String total = rs23.getString("totAmount");
            System.out.println(total);
            
            if(total == null){
            
                tot1 = 0;
            }
            else if(total != null){
            Double tot = Double.parseDouble(total);
            
            tot1 = tot;
            }
        }
        
        String sql2 = "SELECT SUM(amount) As totAmount2 FROM expenditure WHERE paidDate >= '2018/12/01' and paidDate <= '2018/12/31'" ;
        pst33 = con.prepareStatement(sql2);
        rs24 = pst33.executeQuery();
        
        if(rs24.next()){
        
            String total2 = rs24.getString("totAmount2");
            System.out.println(total2);
            
            if(total2 == null){
            
                tot2 = 0;
            }
            else if(total2 != null){
            Double tot = Double.parseDouble(total2);
            
            tot2 = tot;
            }
            
        }
        
        
        String sql3 = "SELECT SUM(amount) As totAmount3 FROM payment WHERE paidDate >= '2018/12/01' and paidDate <= '2018/12/31'" ;
        pst44 = con.prepareStatement(sql3);
        rs25 = pst44.executeQuery();
        
        if(rs25.next()){
        
            String total3 = rs25.getString("totAmount3");
            System.out.println(total3);
            
            if(total3 == null){
            
                tot3 = 0;
            }
            else if(total3 != null){
            Double tot = Double.parseDouble(total3);
            
            tot3 = tot;
            }
            
        }
        
        String sql4 = "SELECT SUM(salary) As totAmount4 FROM payroll WHERE paidDate >= '2018/12/01' and paidDate <= '2018/12/31'" ;
        pst55 = con.prepareStatement(sql4);
        rs26 = pst55.executeQuery();
        
        if(rs26.next()){
        
            String total4 = rs26.getString("totAmount4");
            System.out.println(total4);
            
            if(total4 == null){
            
                tot4 = 0;
            }
            else if(total4 != null){
            Double tot = Double.parseDouble(total4);
            
            tot4 = tot;
            }
            
        }
          
        
        }catch(SQLException e){
        
            
        }
            
        }
      
      
        
        
   
        
      //*****************************************************************************************************************************  
      //*****************************************************************************************************************************
      //*****************************************************************************************************************************
        
 
        
        DefaultCategoryDataset dcd = new DefaultCategoryDataset();
     
        
        dcd.setValue(tot1,"Expences","Vehicles");
        dcd.setValue(tot2,"Expences","Warehouses");
        dcd.setValue(tot3,"Expences","Manufacturer Payment");
        dcd.setValue(tot4,"Expences","Salaries");
        
        
        JFreeChart jchart = ChartFactory.createBarChart("Agency Expences", "Expence Type", "Expence Value Rs.", dcd, PlotOrientation.VERTICAL, true , true, false);
        
        CategoryPlot plot = jchart.getCategoryPlot();
      
        plot.setBackgroundPaint(new Color(187, 224, 103));
        plot.setRangeGridlinePaint(Color.black);
        
        //............color bar.........................
//        ((BarRenderer)plot.getRenderer()).setBarPainter(new StandardBarPainter());
//
//         BarRenderer r = (BarRenderer)jchart.getCategoryPlot().getRenderer();
//         r.setSeriesPaint(0, Color.blue);
//         r.setSeriesPaint(1, Color.CYAN);
//         r.setSeriesPaint(2, Color.green);
//         r.setSeriesPaint(3, Color.MAGENTA);
       


        //..............................................
        
        
        ChartFrame chartFrm = new ChartFrame("Expences",jchart,true);
        chartFrm.setVisible(false);
        chartFrm.setSize(500, 400);
        
        ChartPanel chartPanel = new ChartPanel(jchart);
        
        pnlReport.removeAll();
        pnlReport.add(chartPanel);
        pnlReport.updateUI();
        
        String tot11 = String.valueOf(tot1);
        vBox.setText(tot11);
        
        String tot22 = String.valueOf(tot2);
        wBox.setText(tot22);
        
        String tot33 = String.valueOf(tot3);
        pBox.setText(tot33);
        
        String tot44 = String.valueOf(tot4);
        sBox.setText(tot44);
        
        
        
        
        
        
        
        
        
        
        
        
    }//GEN-LAST:event_showButActionPerformed

    private void combo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo1ActionPerformed
        // TODO add your handling code here:
        
        s = (String) combo1.getSelectedItem();
       // JOptionPane.showMessageDialog(this," You have Selected " + s);
        
        
    }//GEN-LAST:event_combo1ActionPerformed

    private void combo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo2ActionPerformed
        
         p = (String) combo2.getSelectedItem();
       // JOptionPane.showMessageDialog(this," You have Selected " + p);
        
    }//GEN-LAST:event_combo2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        //navigate to Main UI
        MainUI m10 = new MainUI();
        m10.setVisible(true);
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        m10.setLocation(dim.width/2-this.getSize().width/2,dim.height/2-this.getSize().height/2);
        this.dispose();
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       
        //navigate to back
        MonthlySummaryType m11 = new MonthlySummaryType();
        m11.setVisible(true);
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        m11.setLocation(dim.width/2-this.getSize().width/2,dim.height/2-this.getSize().height/2);
        this.dispose();
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MonthlySummaryUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MonthlySummaryUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MonthlySummaryUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MonthlySummaryUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MonthlySummaryUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> combo1;
    private javax.swing.JComboBox<String> combo2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel pBox;
    private javax.swing.JPanel pnlReport;
    private javax.swing.JLabel sBox;
    private javax.swing.JButton showBut;
    private javax.swing.JLabel vBox;
    private javax.swing.JLabel wBox;
    // End of variables declaration//GEN-END:variables

    private String s; 
    private String p;
    private double tot1;
    private double tot2;
    private double tot3;
    private double tot4;
    
    
  
}
