/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fissmda.Vehicle_Subsystem;

import fissmda.Vehicle_Subsystem.DBConnection;
import fissmda.MainUI;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author MaC BrAvO
 */
public class AddVehicleUI extends javax.swing.JFrame {
    
    Connection con = null;
    PreparedStatement pst1 = null;
    /**
     * Creates new form AddVehicleUI
     */
    public AddVehicleUI() {
        initComponents();
        try {
            con = DBConnection.getConnection();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AddVehicleUI.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(AddVehicleUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        //open the current jFrame in center of the screen
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
    }
    
    public boolean isInt (String year1)
    {
        try
        {
            Integer.parseInt(year1);
        }
        catch(NumberFormatException e)
            
        {
            return false;
        }
        catch(NullPointerException e)
        {
            return false;
        }
        return true;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        PannelRight = new javax.swing.JPanel();
        vehiclemodel = new javax.swing.JTextField();
        vehiclemodelname = new javax.swing.JLabel();
        vehiclebrand = new javax.swing.JTextField();
        vehicletypename = new javax.swing.JLabel();
        vehiclefueltype = new javax.swing.JTextField();
        vehiclebrandname = new javax.swing.JLabel();
        vehiclenumber = new javax.swing.JTextField();
        vehiclenumbername = new javax.swing.JLabel();
        BasicInformationLabel1 = new javax.swing.JLabel();
        vehiclemodelyearname = new javax.swing.JLabel();
        vehicletype = new javax.swing.JTextField();
        vehiclefueltypename = new javax.swing.JLabel();
        vehiclemodelyear = new javax.swing.JTextField();
        cancelbutton = new javax.swing.JButton();
        addvehiclebutton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        PannelLeft = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1276, 815));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(137, 229, 45));
        jPanel1.setPreferredSize(new java.awt.Dimension(1276, 815));

        PannelRight.setBackground(new java.awt.Color(153, 153, 91));
        PannelRight.setPreferredSize(new java.awt.Dimension(1000, 866));

        vehiclemodel.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N

        vehiclemodelname.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        vehiclemodelname.setForeground(new java.awt.Color(255, 255, 255));
        vehiclemodelname.setText("Vehicle Model");

        vehiclebrand.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N

        vehicletypename.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        vehicletypename.setForeground(new java.awt.Color(255, 255, 255));
        vehicletypename.setText("Vehicle Type");

        vehiclefueltype.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N

        vehiclebrandname.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        vehiclebrandname.setForeground(new java.awt.Color(255, 255, 255));
        vehiclebrandname.setText("Vehicle Brand");

        vehiclenumber.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        vehiclenumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vehiclenumberActionPerformed(evt);
            }
        });

        vehiclenumbername.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        vehiclenumbername.setForeground(new java.awt.Color(255, 255, 255));
        vehiclenumbername.setText("Vehicle Number");

        BasicInformationLabel1.setFont(new java.awt.Font("DejaVu Sans Light", 1, 26)); // NOI18N
        BasicInformationLabel1.setForeground(new java.awt.Color(255, 255, 255));
        BasicInformationLabel1.setText("Vehicle Details");

        vehiclemodelyearname.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        vehiclemodelyearname.setForeground(new java.awt.Color(255, 255, 255));
        vehiclemodelyearname.setText("Model Year");

        vehicletype.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        vehicletype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vehicletypeActionPerformed(evt);
            }
        });

        vehiclefueltypename.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        vehiclefueltypename.setForeground(new java.awt.Color(255, 255, 255));
        vehiclefueltypename.setText("Fuel Type");

        vehiclemodelyear.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N

        cancelbutton.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        cancelbutton.setText("CANCEL");
        cancelbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelbuttonActionPerformed(evt);
            }
        });

        addvehiclebutton.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        addvehiclebutton.setText("ADD VEHICLE");
        addvehiclebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addvehiclebuttonActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fissmda/ButtonImages/addVehicle_title.png"))); // NOI18N

        javax.swing.GroupLayout PannelRightLayout = new javax.swing.GroupLayout(PannelRight);
        PannelRight.setLayout(PannelRightLayout);
        PannelRightLayout.setHorizontalGroup(
            PannelRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PannelRightLayout.createSequentialGroup()
                .addGroup(PannelRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PannelRightLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(BasicInformationLabel1))
                    .addGroup(PannelRightLayout.createSequentialGroup()
                        .addGap(202, 202, 202)
                        .addGroup(PannelRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PannelRightLayout.createSequentialGroup()
                                .addGroup(PannelRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(vehicletypename)
                                    .addComponent(vehiclemodelyearname)
                                    .addComponent(vehiclefueltypename)
                                    .addComponent(vehiclebrandname)
                                    .addComponent(vehiclemodelname))
                                .addGap(34, 34, 34)
                                .addGroup(PannelRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(vehicletype, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(vehiclemodel, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(vehiclemodelyear, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(vehiclefueltype, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(vehiclebrand, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(PannelRightLayout.createSequentialGroup()
                                .addComponent(vehiclenumbername)
                                .addGap(18, 18, 18)
                                .addComponent(vehiclenumber, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(0, 600, Short.MAX_VALUE))
            .addGroup(PannelRightLayout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addComponent(cancelbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(241, 241, 241)
                .addComponent(addvehiclebutton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PannelRightLayout.setVerticalGroup(
            PannelRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PannelRightLayout.createSequentialGroup()
                .addGroup(PannelRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PannelRightLayout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(BasicInformationLabel1))
                    .addGroup(PannelRightLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29)
                .addGroup(PannelRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vehiclenumbername)
                    .addComponent(vehiclenumber, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(PannelRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vehiclemodel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vehiclemodelname))
                .addGap(34, 34, 34)
                .addGroup(PannelRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vehicletype, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vehicletypename))
                .addGap(41, 41, 41)
                .addGroup(PannelRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vehiclemodelyear, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vehiclemodelyearname))
                .addGap(36, 36, 36)
                .addGroup(PannelRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vehiclefueltype, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vehiclefueltypename))
                .addGap(33, 33, 33)
                .addGroup(PannelRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vehiclebrand, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vehiclebrandname))
                .addGap(102, 102, 102)
                .addGroup(PannelRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addvehiclebutton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(150, Short.MAX_VALUE))
        );

        PannelLeft.setBackground(new java.awt.Color(137, 229, 45));
        PannelLeft.setPreferredSize(new java.awt.Dimension(350, 58));

        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fissmda/ButtonImages/greenBack.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fissmda/ButtonImages/greenHome.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fissmda/ButtonImages/CompanyLogoSmall(new).png"))); // NOI18N

        javax.swing.GroupLayout PannelLeftLayout = new javax.swing.GroupLayout(PannelLeft);
        PannelLeft.setLayout(PannelLeftLayout);
        PannelLeftLayout.setHorizontalGroup(
            PannelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PannelLeftLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PannelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PannelLeftLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PannelLeftLayout.createSequentialGroup()
                        .addGap(0, 63, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(73, 73, 73))))
            .addGroup(PannelLeftLayout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(jLabel2)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        PannelLeftLayout.setVerticalGroup(
            PannelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PannelLeftLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(PannelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(PannelLeftLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(105, 105, 105))
                    .addGroup(PannelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(49, 49, 49)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(PannelLeft, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PannelRight, javax.swing.GroupLayout.PREFERRED_SIZE, 1268, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PannelRight, javax.swing.GroupLayout.DEFAULT_SIZE, 815, Short.MAX_VALUE)
            .addComponent(PannelLeft, javax.swing.GroupLayout.DEFAULT_SIZE, 815, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1299, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        
    }//GEN-LAST:event_jLabel3MouseClicked

    private void addvehiclebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addvehiclebuttonActionPerformed
        
        //Connecting to DataBase
        String VehicleModel = vehiclemodel.getText();
        String VehicleType = vehicletype.getText();
        String VehicleBrand = vehiclebrand.getText();
        String VehicleModelYear = vehiclemodelyear.getText();
        String VehicleFuelType = vehiclefueltype.getText();
        String VehicleNumber = vehiclenumber.getText();
        
        if(VehicleModel.isEmpty() || VehicleType.isEmpty() || VehicleBrand.isEmpty() || VehicleModelYear.isEmpty() || VehicleFuelType.isEmpty() || VehicleNumber.isEmpty())
        {
            JOptionPane.showMessageDialog(null,"This Field can not be Empty");
        }
        else if(!isInt(VehicleModelYear))
        {
            JOptionPane.showMessageDialog(null,"Year must be an Integer");
        }
        else
        {
        
            try {
            String q1 = "INSERT INTO vehicle (model,type,brand,vehicle_number,model_year,fuel_type) values (?,?,?,?,?,?)";
            int year = Integer.parseInt(VehicleModelYear);
            pst1 = con.prepareStatement(q1);
            pst1.setString(1, VehicleModel);
            pst1.setString(2, VehicleType);
            pst1.setString(3, VehicleBrand);
            pst1.setString(4, VehicleNumber);
            pst1.setInt(5, year);
            pst1.setString(6, VehicleFuelType);

            pst1.executeUpdate();
            
            JOptionPane.showMessageDialog(null,"Successful");

            //Clear Fields
                vehiclemodel.setText(null);
                vehicletype.setText(null);
                vehiclebrand.setText(null);
                vehiclemodelyear.setText(null);
                vehiclefueltype.setText(null);
                vehiclenumber.setText(null);
            
            
        
        }
        catch (SQLException ex) {
            Logger.getLogger(AddVehicleUI.class.getName()).log(Level.SEVERE, null, ex);
            
        }
    }
               

    }//GEN-LAST:event_addvehiclebuttonActionPerformed

    private void vehicletypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vehicletypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vehicletypeActionPerformed

    private void vehiclenumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vehiclenumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vehiclenumberActionPerformed

    private void cancelbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelbuttonActionPerformed
        
        VehicleUI ui3 = new VehicleUI();
        ui3.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_cancelbuttonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        VehicleUI ui = new VehicleUI();
        ui.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        MainUI ui = new MainUI();
        ui.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddVehicleUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddVehicleUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddVehicleUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddVehicleUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddVehicleUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BasicInformationLabel1;
    private javax.swing.JPanel PannelLeft;
    private javax.swing.JPanel PannelRight;
    private javax.swing.JButton addvehiclebutton;
    private javax.swing.JButton cancelbutton;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField vehiclebrand;
    private javax.swing.JLabel vehiclebrandname;
    private javax.swing.JTextField vehiclefueltype;
    private javax.swing.JLabel vehiclefueltypename;
    private javax.swing.JTextField vehiclemodel;
    private javax.swing.JLabel vehiclemodelname;
    private javax.swing.JTextField vehiclemodelyear;
    private javax.swing.JLabel vehiclemodelyearname;
    private javax.swing.JTextField vehiclenumber;
    private javax.swing.JLabel vehiclenumbername;
    private javax.swing.JTextField vehicletype;
    private javax.swing.JLabel vehicletypename;
    // End of variables declaration//GEN-END:variables
}
