/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fissmda.Vehicle_Subsystem;

import fissmda.DBConnection;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author MaC BrAvO
 */
public class AddVehicleUI extends javax.swing.JFrame {
    
    Connection con = null;
    PreparedStatement pst1 = null;
    /**
     * Creates new form AddVehicleUI
     */
    public AddVehicleUI() {
        initComponents();
        try {
            con = DBConnection.getConnection();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AddVehicleUI.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(AddVehicleUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PannelLeft = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        PannelRight = new javax.swing.JPanel();
        vehiclemodel = new javax.swing.JTextField();
        vehiclemodelname = new javax.swing.JLabel();
        vehicletype = new javax.swing.JTextField();
        vehicletypename = new javax.swing.JLabel();
        vehiclebrand = new javax.swing.JTextField();
        vehiclebrandname = new javax.swing.JLabel();
        vehiclenumber = new javax.swing.JTextField();
        vehiclenumbername = new javax.swing.JLabel();
        BasicInformationLabel1 = new javax.swing.JLabel();
        vehiclemodelyearname = new javax.swing.JLabel();
        vehiclemodelyear = new javax.swing.JTextField();
        vehiclefueltypename = new javax.swing.JLabel();
        vehiclefueltype = new javax.swing.JTextField();
        cancelbutton = new javax.swing.JButton();
        addvehiclebutton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        PannelLeft.setBackground(new java.awt.Color(204, 0, 0));

        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("DejaVu Sans Light", 1, 20)); // NOI18N
        jLabel2.setText("Add Vehicle");

        javax.swing.GroupLayout PannelLeftLayout = new javax.swing.GroupLayout(PannelLeft);
        PannelLeft.setLayout(PannelLeftLayout);
        PannelLeftLayout.setHorizontalGroup(
            PannelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PannelLeftLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PannelLeftLayout.setVerticalGroup(
            PannelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PannelLeftLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(PannelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        PannelRight.setBackground(new java.awt.Color(0, 153, 0));

        vehiclemodelname.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        vehiclemodelname.setForeground(new java.awt.Color(255, 255, 255));
        vehiclemodelname.setText("Vehicle Model");

        vehicletypename.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        vehicletypename.setForeground(new java.awt.Color(255, 255, 255));
        vehicletypename.setText("Vehicle Type");

        vehiclebrandname.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        vehiclebrandname.setForeground(new java.awt.Color(255, 255, 255));
        vehiclebrandname.setText("Vehicle Brand");

        vehiclenumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vehiclenumberActionPerformed(evt);
            }
        });

        vehiclenumbername.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        vehiclenumbername.setForeground(new java.awt.Color(255, 255, 255));
        vehiclenumbername.setText("Vehicle Number");

        BasicInformationLabel1.setFont(new java.awt.Font("DejaVu Sans Light", 1, 26)); // NOI18N
        BasicInformationLabel1.setForeground(new java.awt.Color(255, 255, 255));
        BasicInformationLabel1.setText("Vehicle Details");

        vehiclemodelyearname.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        vehiclemodelyearname.setForeground(new java.awt.Color(255, 255, 255));
        vehiclemodelyearname.setText("Model Year");

        vehiclemodelyear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vehiclemodelyearActionPerformed(evt);
            }
        });

        vehiclefueltypename.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        vehiclefueltypename.setForeground(new java.awt.Color(255, 255, 255));
        vehiclefueltypename.setText("Fuel Type");

        cancelbutton.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        cancelbutton.setText("CANCLE");
        cancelbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelbuttonActionPerformed(evt);
            }
        });

        addvehiclebutton.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        addvehiclebutton.setText("ADD VEHICLE");
        addvehiclebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addvehiclebuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PannelRightLayout = new javax.swing.GroupLayout(PannelRight);
        PannelRight.setLayout(PannelRightLayout);
        PannelRightLayout.setHorizontalGroup(
            PannelRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PannelRightLayout.createSequentialGroup()
                .addGroup(PannelRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PannelRightLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(BasicInformationLabel1))
                    .addGroup(PannelRightLayout.createSequentialGroup()
                        .addGroup(PannelRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PannelRightLayout.createSequentialGroup()
                                .addGap(514, 514, 514)
                                .addComponent(cancelbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(70, 70, 70))
                            .addGroup(PannelRightLayout.createSequentialGroup()
                                .addGap(227, 227, 227)
                                .addGroup(PannelRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(vehiclemodelname)
                                    .addComponent(vehicletypename)
                                    .addComponent(vehiclenumbername))
                                .addGap(27, 27, 27)
                                .addGroup(PannelRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(vehiclenumber, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(vehicletype, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(vehiclemodel, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(108, 108, 108)))
                        .addGroup(PannelRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addvehiclebutton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(PannelRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(PannelRightLayout.createSequentialGroup()
                                    .addComponent(vehiclebrandname)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(vehiclebrand, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(PannelRightLayout.createSequentialGroup()
                                    .addGroup(PannelRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(vehiclefueltypename)
                                        .addComponent(vehiclemodelyearname))
                                    .addGap(58, 58, 58)
                                    .addGroup(PannelRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(vehiclemodelyear, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(vehiclefueltype, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addGap(0, 170, Short.MAX_VALUE))
        );
        PannelRightLayout.setVerticalGroup(
            PannelRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PannelRightLayout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(BasicInformationLabel1)
                .addGap(24, 24, 24)
                .addGroup(PannelRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PannelRightLayout.createSequentialGroup()
                        .addGroup(PannelRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(vehiclenumbername)
                            .addComponent(vehiclenumber, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(PannelRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(vehiclemodel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(vehiclemodelname))
                        .addGap(18, 18, 18)
                        .addGroup(PannelRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(vehicletype, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(vehicletypename))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 159, Short.MAX_VALUE)
                        .addGroup(PannelRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cancelbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addvehiclebutton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(54, 54, 54))
                    .addGroup(PannelRightLayout.createSequentialGroup()
                        .addGroup(PannelRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(vehiclemodelyear, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(vehiclemodelyearname))
                        .addGap(18, 18, 18)
                        .addGroup(PannelRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(vehiclefueltype, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(vehiclefueltypename))
                        .addGap(18, 18, 18)
                        .addGroup(PannelRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(vehiclebrand, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(vehiclebrandname))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PannelLeft, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PannelRight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PannelLeft, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(PannelRight, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        
    }//GEN-LAST:event_jLabel3MouseClicked

    private void addvehiclebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addvehiclebuttonActionPerformed
        
        //Connecting to DataBase
        String VehicleModel = vehiclemodel.getText();
        String VehicleType = vehicletype.getText();
        String VehicleBrand = vehiclebrand.getText();
        String VehicleModelYear = vehiclemodelyear.getText();
        String VehicleFuelType = vehiclefueltype.getText();
        String VehicleNumber = vehiclenumber.getText();
        int year = Integer.parseInt(VehicleModelYear);
        
        try {
            String q1 = "INSERT INTO vehicle (model,type,brand,vehicle_number,model_year,fuel_type) values (?,?,?,?,?,?)";
        pst1 = con.prepareStatement(q1);
        pst1.setString(1, VehicleModel);
        pst1.setString(2, VehicleType);
        pst1.setString(3, VehicleBrand);
        pst1.setString(4, VehicleNumber);
        pst1.setInt(5, year);
        pst1.setString(6, VehicleFuelType);
          
        pst1.executeUpdate();
        
        //Showing Successful Message Page
        AddVehicleShowPage showpage1 = new AddVehicleShowPage();
        showpage1.setVisible(true);
        this.dispose();
        
        }
        catch (SQLException ex) {
            Logger.getLogger(AddVehicleUI.class.getName()).log(Level.SEVERE, null, ex);
            
        }
               

    }//GEN-LAST:event_addvehiclebuttonActionPerformed

    private void vehiclemodelyearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vehiclemodelyearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vehiclemodelyearActionPerformed

    private void vehiclenumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vehiclenumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vehiclenumberActionPerformed

    private void cancelbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelbuttonActionPerformed
        
        VehicleUI ui3 = new VehicleUI();
        ui3.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_cancelbuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddVehicleUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddVehicleUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddVehicleUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddVehicleUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddVehicleUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BasicInformationLabel1;
    private javax.swing.JPanel PannelLeft;
    private javax.swing.JPanel PannelRight;
    private javax.swing.JButton addvehiclebutton;
    private javax.swing.JButton cancelbutton;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField vehiclebrand;
    private javax.swing.JLabel vehiclebrandname;
    private javax.swing.JTextField vehiclefueltype;
    private javax.swing.JLabel vehiclefueltypename;
    private javax.swing.JTextField vehiclemodel;
    private javax.swing.JLabel vehiclemodelname;
    private javax.swing.JTextField vehiclemodelyear;
    private javax.swing.JLabel vehiclemodelyearname;
    private javax.swing.JTextField vehiclenumber;
    private javax.swing.JLabel vehiclenumbername;
    private javax.swing.JTextField vehicletype;
    private javax.swing.JLabel vehicletypename;
    // End of variables declaration//GEN-END:variables
}
