/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fissmda.Vehicle_Subsystem;

import fissmda.Vehicle_Subsystem.DBConnection;
import fissmda.MainUI;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author MaC BrAvO
 */
public class AddVehicleLogUI extends javax.swing.JFrame {
    
    Connection connection = null;
    PreparedStatement ps = null;
    ResultSet rs = null;

    /**
     * Creates new form AddVehicleLogUI
     */
    public AddVehicleLogUI() {
        initComponents();
        
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
        
        try {
            //create objects
            connection = DBConnection.getConnection();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(UpdateVehicleDetailsUI.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(UpdateVehicleDetailsUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        fillVehicleCombobox();
    }
    
    public void fillVehicleCombobox()
    {
        try {
            String q = "SELECT * FROM vehicle";
            ps = connection.prepareStatement(q);
            rs = ps.executeQuery(q);
            
            //remove all available items 
            selectvehiclecombo5.removeAllItems();
            selectvehiclecombo5.addItem("Select Vehicle");
            
            while(rs.next()){
                
                selectvehiclecombo5.addItem(rs.getString("vehicle_number") );
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(RemoveVehicleUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    
    }
    
    public boolean isInt (String amount1)
    {
        try
        {
            Integer.parseInt(amount1);
        }
        catch(NumberFormatException e)
            
        {
            return false;
        }
        catch(NullPointerException e)
        {
            return false;
        }
        return true;
    }
    
    public int VehicleID1(String vehicle_number)
    {
        int vehicleId = 0;
        
        
        String vID = "SELECT vID FROM vehicle WHERE vehicle_number = ?";
        
        try
        {
            ps = connection.prepareStatement(vID);
            ps.setString(1, vehicle_number);
            ResultSet rs = ps.executeQuery();
            
            while(rs.next())
            {
                vehicleId = (int) rs.getInt("vID");
            }
            return vehicleId;
        }
        
        catch (SQLException ex) {
            Logger.getLogger(RemoveVehicleUI.class.getName()).log(Level.SEVERE, null, ex);
            return vehicleId;
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        PannelLeft = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        PannelRight = new javax.swing.JPanel();
        amounttextfield = new javax.swing.JTextField();
        amounttext = new javax.swing.JLabel();
        cancelbutton5 = new javax.swing.JButton();
        addbutton = new javax.swing.JButton();
        selectexpanditure = new javax.swing.JLabel();
        selectvehicle2 = new javax.swing.JLabel();
        selectvehiclecombo5 = new javax.swing.JComboBox<>();
        selectexpanditurecombo = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1276, 815));

        jPanel1.setBackground(new java.awt.Color(137, 229, 45));
        jPanel1.setPreferredSize(new java.awt.Dimension(1276, 815));

        PannelLeft.setBackground(new java.awt.Color(137, 229, 45));
        PannelLeft.setPreferredSize(new java.awt.Dimension(350, 58));

        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fissmda/ButtonImages/greenBack.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fissmda/ButtonImages/greenHome.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PannelLeftLayout = new javax.swing.GroupLayout(PannelLeft);
        PannelLeft.setLayout(PannelLeftLayout);
        PannelLeftLayout.setHorizontalGroup(
            PannelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PannelLeftLayout.createSequentialGroup()
                .addGroup(PannelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PannelLeftLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3))
                    .addGroup(PannelLeftLayout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        PannelLeftLayout.setVerticalGroup(
            PannelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PannelLeftLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(PannelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PannelLeftLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        PannelRight.setBackground(new java.awt.Color(153, 153, 91));
        PannelRight.setPreferredSize(new java.awt.Dimension(1000, 866));

        amounttextfield.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        amounttextfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amounttextfieldActionPerformed(evt);
            }
        });

        amounttext.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        amounttext.setForeground(new java.awt.Color(255, 255, 255));
        amounttext.setText("Amount");

        cancelbutton5.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        cancelbutton5.setText("CANCEL");
        cancelbutton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelbutton5ActionPerformed(evt);
            }
        });

        addbutton.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        addbutton.setText("ADD ");
        addbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbuttonActionPerformed(evt);
            }
        });

        selectexpanditure.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        selectexpanditure.setForeground(new java.awt.Color(255, 255, 255));
        selectexpanditure.setText("Select Expenditure");

        selectvehicle2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        selectvehicle2.setForeground(new java.awt.Color(255, 255, 255));
        selectvehicle2.setText("Select Vehicle");

        selectvehiclecombo5.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        selectvehiclecombo5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Vehicle" }));
        selectvehiclecombo5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectvehiclecombo5ActionPerformed(evt);
            }
        });

        selectexpanditurecombo.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        selectexpanditurecombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Expenditure", "Fuel ", "Liscense", "Repair", "Services", " " }));
        selectexpanditurecombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectexpanditurecomboActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fissmda/ButtonImages/addVehicleLog_title.png"))); // NOI18N

        javax.swing.GroupLayout PannelRightLayout = new javax.swing.GroupLayout(PannelRight);
        PannelRight.setLayout(PannelRightLayout);
        PannelRightLayout.setHorizontalGroup(
            PannelRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PannelRightLayout.createSequentialGroup()
                .addContainerGap(168, Short.MAX_VALUE)
                .addGroup(PannelRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(selectexpanditure, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(selectvehicle2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(PannelRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(selectvehiclecombo5, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(selectexpanditurecombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(650, 650, 650))
            .addGroup(PannelRightLayout.createSequentialGroup()
                .addGroup(PannelRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PannelRightLayout.createSequentialGroup()
                        .addGap(223, 223, 223)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 485, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PannelRightLayout.createSequentialGroup()
                        .addGap(218, 218, 218)
                        .addComponent(amounttext)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(amounttextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PannelRightLayout.createSequentialGroup()
                        .addGap(178, 178, 178)
                        .addComponent(cancelbutton5, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(198, 198, 198)
                        .addComponent(addbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PannelRightLayout.setVerticalGroup(
            PannelRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PannelRightLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(99, 99, 99)
                .addGroup(PannelRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(selectvehiclecombo5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selectvehicle2))
                .addGroup(PannelRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PannelRightLayout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addGroup(PannelRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(amounttext)
                            .addComponent(amounttextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(PannelRightLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(PannelRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(selectexpanditurecombo, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(selectexpanditure))))
                .addGap(146, 146, 146)
                .addGroup(PannelRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelbutton5, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(377, Short.MAX_VALUE))
        );

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fissmda/ButtonImages/CompanyLogoSmall(new).png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PannelLeft, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PannelRight, javax.swing.GroupLayout.PREFERRED_SIZE, 1268, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PannelRight, javax.swing.GroupLayout.PREFERRED_SIZE, 961, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(PannelLeft, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(jLabel2)))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1288, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 837, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 37, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked

    }//GEN-LAST:event_jLabel3MouseClicked

    private void addbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addbuttonActionPerformed

        //Connecting to DataBase
        String getVehicleItem = selectvehiclecombo5.getSelectedItem().toString();
        String getExpenditure = selectexpanditurecombo.getSelectedItem().toString();
        String Amount = amounttextfield.getText();
        
        int amount1;
        
        if(getVehicleItem.equals("Select Vehicle"))
        {
            JOptionPane.showMessageDialog(null,"Please select a Vehicle");
        }
        else if(getExpenditure.equals("Select Expenditure"))
        {
            JOptionPane.showMessageDialog(null,"Please Select a Expenditure to Add");
        }
        else if(Amount.isEmpty())
        {
            JOptionPane.showMessageDialog(null,"Amount Can not be Empty");
        }
        else if(!isInt(Amount))
        
        {
            JOptionPane.showMessageDialog(null,"Amount Should be an Integer Value. Please Enter Valid Value");
            amounttextfield.setText(null);
        }
        else
        {
            int vehicleId = VehicleID1(getVehicleItem);
            
            try {
            String q1 = "INSERT INTO vehicle_log (vID,amount,expenditure) values (?,?,?)";
            
            int amount2 = Integer.parseInt(Amount);
         
            ps = connection.prepareStatement(q1);
            
            ps.setInt(1, vehicleId);
            ps.setInt(2, amount2);
            ps.setString(3, getExpenditure);
            
            
            ps.executeUpdate();
            JOptionPane.showMessageDialog(null,"Successful");

        
        }
        catch (SQLException ex) {
            Logger.getLogger(AddVehicleUI.class.getName()).log(Level.SEVERE, null, ex);
            
        }
            
        }
        
        amounttextfield.setText(null);
        
        
        

        
        
        
    }//GEN-LAST:event_addbuttonActionPerformed

    private void cancelbutton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelbutton5ActionPerformed

        VehicleUI ui3 = new VehicleUI();
        ui3.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_cancelbutton5ActionPerformed

    private void amounttextfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amounttextfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_amounttextfieldActionPerformed

    private void selectexpanditurecomboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectexpanditurecomboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selectexpanditurecomboActionPerformed

    private void selectvehiclecombo5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectvehiclecombo5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selectvehiclecombo5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        VehicleUI ui = new VehicleUI();
        ui.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        MainUI ui = new MainUI();
        ui.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddVehicleLogUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddVehicleLogUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddVehicleLogUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddVehicleLogUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddVehicleLogUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PannelLeft;
    private javax.swing.JPanel PannelRight;
    private javax.swing.JButton addbutton;
    private javax.swing.JLabel amounttext;
    private javax.swing.JTextField amounttextfield;
    private javax.swing.JButton cancelbutton5;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel selectexpanditure;
    private javax.swing.JComboBox<String> selectexpanditurecombo;
    private javax.swing.JLabel selectvehicle2;
    private javax.swing.JComboBox<String> selectvehiclecombo5;
    // End of variables declaration//GEN-END:variables
}
