/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fissmda.Warehouse_Subsystem.ExpenditureMS.addExpenditure;

import fissmda.Warehouse_Subsystem.DBConnection;
import fissmda.Warehouse_Subsystem.ExpenditureMS.EMS_UI;
import fissmda.Warehouse_Subsystem.ExpenditureMS.ExpenditureHandler;
import fissmda.Warehouse_Subsystem.WMSUI;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.DateFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author melan
 */
public class AddExpenditure extends javax.swing.JFrame {

    /**
     * Creates new form AddExpenditure
     */
    
    Connection con;
    PreparedStatement ps;
    ResultSet rs;
    
    public AddExpenditure() {
        initComponents();
        
              //Generate in Center at the Runtime 
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);

         //establish connectiion
        try{
            
            con = DBConnection.getConnection();
            fillCombo();
            
        }catch(Exception e){
            e.printStackTrace();
        }
        
    }
    
   
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PannelLeft = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        PannelRight = new javax.swing.JPanel();
        billStartDate = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        WarehouseListCombo = new javax.swing.JComboBox<>();
        selectBill = new javax.swing.JComboBox<>();
        billEndDate = new com.toedter.calendar.JDateChooser();
        billAmount = new javax.swing.JTextField();
        cancleBtn = new javax.swing.JButton();
        addExpenditure = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        Demo1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1276, 815));
        setMinimumSize(new java.awt.Dimension(1276, 815));
        setPreferredSize(new java.awt.Dimension(1276, 815));
        setResizable(false);

        PannelLeft.setBackground(new java.awt.Color(153, 153, 91));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fissmda/Warehouse_Subsystem/resources/backB.png"))); // NOI18N
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        PannelRight.setBackground(new java.awt.Color(137, 229, 47));

        jLabel1.setBackground(new java.awt.Color(51, 51, 51));
        jLabel1.setFont(new java.awt.Font("DejaVu Sans", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Select Warehouse");

        jLabel4.setBackground(new java.awt.Color(51, 51, 51));
        jLabel4.setFont(new java.awt.Font("DejaVu Sans", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Select Bill ");

        jLabel5.setBackground(new java.awt.Color(51, 51, 51));
        jLabel5.setFont(new java.awt.Font("DejaVu Sans", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Bill Start Date");

        jLabel6.setBackground(new java.awt.Color(51, 51, 51));
        jLabel6.setFont(new java.awt.Font("DejaVu Sans", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("Bill End Date");

        jLabel7.setBackground(new java.awt.Color(51, 51, 51));
        jLabel7.setFont(new java.awt.Font("DejaVu Sans", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("Bill Amount");

        WarehouseListCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Warehouse", " " }));

        selectBill.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "LECO Electricity Bill", "Water Bill", "Telecommumnication / Intenet", " " }));

        cancleBtn.setBackground(new java.awt.Color(255, 51, 102));
        cancleBtn.setText("CANCEL");
        cancleBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancleBtnActionPerformed(evt);
            }
        });

        addExpenditure.setBackground(new java.awt.Color(102, 255, 102));
        addExpenditure.setText("ADD EXPENDITURE");
        addExpenditure.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addExpenditureActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("DejaVu Sans", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Add Expense to Warehouse");

        Demo1.setBackground(new java.awt.Color(102, 255, 102));
        Demo1.setText("Demo");
        Demo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Demo1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PannelRightLayout = new javax.swing.GroupLayout(PannelRight);
        PannelRight.setLayout(PannelRightLayout);
        PannelRightLayout.setHorizontalGroup(
            PannelRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PannelRightLayout.createSequentialGroup()
                .addGroup(PannelRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PannelRightLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabel2))
                    .addGroup(PannelRightLayout.createSequentialGroup()
                        .addGap(404, 404, 404)
                        .addGroup(PannelRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PannelRightLayout.createSequentialGroup()
                                .addComponent(Demo1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(cancleBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(addExpenditure, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PannelRightLayout.createSequentialGroup()
                                .addGroup(PannelRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel1))
                                .addGap(68, 68, 68)
                                .addGroup(PannelRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(billEndDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(billStartDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(selectBill, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(WarehouseListCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(billAmount))))))
                .addContainerGap(913, Short.MAX_VALUE))
        );
        PannelRightLayout.setVerticalGroup(
            PannelRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PannelRightLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel2)
                .addGap(130, 130, 130)
                .addGroup(PannelRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(WarehouseListCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PannelRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(selectBill, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGroup(PannelRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PannelRightLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(billStartDate, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(40, 40, 40)
                .addGroup(PannelRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(billEndDate, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(PannelRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PannelRightLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jLabel7))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PannelRightLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(billAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(79, 79, 79)
                .addGroup(PannelRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancleBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Demo1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addExpenditure, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(68, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout PannelLeftLayout = new javax.swing.GroupLayout(PannelLeft);
        PannelLeft.setLayout(PannelLeftLayout);
        PannelLeftLayout.setHorizontalGroup(
            PannelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PannelLeftLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(PannelRight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        PannelLeftLayout.setVerticalGroup(
            PannelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PannelLeftLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(PannelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PannelRight, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(PannelLeftLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(0, 587, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PannelLeft, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PannelLeft, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        new EMS_UI().setVisible(true);
        this.setVisible(false);
        
        
       
    }//GEN-LAST:event_jLabel3MouseClicked

    private void cancleBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancleBtnActionPerformed
        // TODO add your handling code here:

        //Asking user to close panel
        int choice = JOptionPane.showConfirmDialog(null, "Do You want to Cancel ?");
        if (choice == 0) {
            //cancel button clicked
            this.setVisible(false);
            new WMSUI().setVisible(true);
        } else {

        }
    }//GEN-LAST:event_cancleBtnActionPerformed

    private void addExpenditureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addExpenditureActionPerformed

        if(!(billAmount.getText().equals("")||selectBill.getSelectedItem().toString().equals("")||WarehouseListCombo.getSelectedItem().toString().equals("")||billStartDate.getDate()==null||billEndDate.getDate()==null)){
       if(billAmount.getText().toString().matches("[0-9]+")){ 
        String amount = billAmount.getText().toString();
        String billType =selectBill.getSelectedItem().toString();
        String selectedWarehouse = WarehouseListCombo.getSelectedItem().toString();
        
        
        
        ExpenditureHandler validE = new ExpenditureHandler(selectedWarehouse,billType,amount);
        
      
                String sqlExc = "select wID from warehouse where warehouse_name = '"+selectedWarehouse+"'";
        
        try{
            ps = con.prepareStatement(sqlExc);
            rs = ps.executeQuery();
            
            //check date field field is null
            
           
            Date stDate = new Date(billStartDate.getDate().getTime());
            Date endDate = new Date(billEndDate.getDate().getTime());
            
            int wID=0;
            while(rs.next()){
            
                
                 wID = rs.getInt(1);
                System.out.println("  "+wID);
            } 
            
            
        
            String sqlExec ="Insert into expenditure (amount,category,arrivalDate,deadLine,warehouse_WID) values(?,?,?,?,?)";
            
            
             int choice = JOptionPane.showConfirmDialog(this, "Do You want to Add to Database");
                            if (choice == 0) {
                                try {
                                    ps = con.prepareStatement(sqlExec);
                                    ps.setString(1, amount);
                                    ps.setString(2,billType);
                                    ps.setDate(3,stDate);
                                    ps.setDate(4,endDate);
                                    ps.setInt(5, wID);
                                    ps.execute();
                                    JOptionPane.showMessageDialog(this, "Successfully Added to Database");
                                } catch (Exception e) {
                                    e.printStackTrace();
                                }
                            }
         
        }catch(Exception e){
            e.printStackTrace();
        }
       }else{
           JOptionPane.showMessageDialog(this, "Amount Field should numerical value");
       }
        }else{
        
             JOptionPane.showMessageDialog(this, "Al the the fields should be completed");

        }
    }//GEN-LAST:event_addExpenditureActionPerformed

    private void Demo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Demo1ActionPerformed
        // TODO add your handling code here:
       WarehouseListCombo.setSelectedIndex(2);
       selectBill.setSelectedIndex(2);
       billAmount.setText("2450");
    }//GEN-LAST:event_Demo1ActionPerformed

    /**
     * @param args the command line argumentswarehouseSelector
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddExpenditure.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddExpenditure.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddExpenditure.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddExpenditure.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddExpenditure().setVisible(true);
            }
        });
    }
    
    
     public void fillCombo() {

        try {

            String sqlExec = "select * from warehouse";
            ps = con.prepareStatement(sqlExec);
            rs = ps.executeQuery();

            while (rs.next()) {
                String getWarehouseName = rs.getString("warehouse_name");
                WarehouseListCombo.addItem(getWarehouseName);
                
                
            }

        } catch (Exception e) {

            JOptionPane.showMessageDialog(this,"Error with Fetch Data");
            e.printStackTrace();

        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Demo1;
    private javax.swing.JPanel PannelLeft;
    private javax.swing.JPanel PannelRight;
    private javax.swing.JComboBox<String> WarehouseListCombo;
    private javax.swing.JButton addExpenditure;
    private javax.swing.JTextField billAmount;
    private com.toedter.calendar.JDateChooser billEndDate;
    private com.toedter.calendar.JDateChooser billStartDate;
    private javax.swing.JButton cancleBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JComboBox<String> selectBill;
    // End of variables declaration//GEN-END:variables
}
